// NCDC Uganda Complete Syllabus Database
// Based on NCDC 2025 Curriculum
// O-Level: S1-S4 (Lower Secondary)
// A-Level: S5-S6 (Advanced Secondary)
// Primary: P1-P7 (Thematic for P1-P3, Subject-based for P4-P7)

export interface NSDCTopic {
  id: string;
  subject: string;
  class_level: number; // 1-7 for P1-P7, 1-6 for S1-S6
  level: "primary" | "o-level" | "a-level";
  term: number; // 1-3
  topic: string;
  subtopics: string[];
  objectives: string[];
  weeks: number;
  competency_focus?: string;
  cross_cutting_theme?: string[];
}

// ============================================
// PRIMARY P1 (Primary One) - Thematic Curriculum
// ============================================

export const P1_ALL_SUBJECTS: NSDCTopic[] = [
  // Language Activities P1
  {
    id: "p1-lang-t1-1",
    subject: "Language Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "Oral Language",
    subtopics: ["Listening", "Speaking", "Vocabulary building"],
    objectives: ["Listen attentively", "Speak clearly", "Build vocabulary"],
    weeks: 2,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["health"],
  },
  {
    id: "p1-lang-t1-2",
    subject: "Language Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "Reading Readiness",
    subtopics: ["Letter sounds", "Word recognition", "Picture reading"],
    objectives: [
      "Identify letter sounds",
      "Recognize simple words",
      "Read pictures",
    ],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p1-lang-t1-3",
    subject: "Language Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "Writing Readiness",
    subtopics: ["Pencil grip", "Tracing", "Drawing"],
    objectives: [
      "Hold pencil correctly",
      "Trace lines and shapes",
      "Draw simple pictures",
    ],
    weeks: 2,
    competency_focus: "developing",
  },
  // Mathematical Activities P1
  {
    id: "p1-math-t1-1",
    subject: "Mathematical Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "Numbers 1-5",
    subtopics: ["Counting", "Ordering", "Matching"],
    objectives: ["Count objects 1-5", "Order numbers", "Match quantities"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "p1-math-t1-2",
    subject: "Mathematical Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "Shapes",
    subtopics: ["Circle", "Square", "Triangle"],
    objectives: ["Identify shapes", "Sort shapes", "Create patterns"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "p1-math-t1-3",
    subject: "Mathematical Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "Measurement",
    subtopics: ["Length", "Weight", "Capacity"],
    objectives: ["Compare lengths", "Compare weights", "Compare amounts"],
    weeks: 2,
    competency_focus: "developing",
  },
  // Environmental Activities P1
  {
    id: "p1-env-t1-1",
    subject: "Environmental Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "My Body",
    subtopics: ["Body parts", "Keeping clean", "Health habits"],
    objectives: ["Identify body parts", "Practice hygiene", "Stay healthy"],
    weeks: 2,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["health"],
  },
  {
    id: "p1-env-t1-2",
    subject: "Environmental Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "My Family",
    subtopics: ["Family members", "Roles", "Helping at home"],
    objectives: ["Identify family members", "Understand roles", "Help at home"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "p1-env-t1-3",
    subject: "Environmental Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "Our School",
    subtopics: ["School areas", "School rules", "Being safe"],
    objectives: ["Know school areas", "Follow rules", "Stay safe"],
    weeks: 2,
    competency_focus: "developing",
  },
  // Religious Activities P1
  {
    id: "p1-rel-t1-1",
    subject: "Religious Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "God our Creator",
    subtopics: ["Creation story", "God's love", "Thanking God"],
    objectives: ["Understand creation", "Feel God's love", "Say thanks to God"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  // Physical Activities P1
  {
    id: "p1-phy-t1-1",
    subject: "Physical Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "Body Movement",
    subtopics: ["Running", "Jumping", "Balancing"],
    objectives: ["Move safely", "Balance body", "Control movements"],
    weeks: 2,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["health"],
  },
  // Creative Activities P1
  {
    id: "p1-art-t1-1",
    subject: "Creative Activities",
    class_level: 1,
    level: "primary",
    term: 1,
    topic: "Art and Craft",
    subtopics: ["Drawing", "Painting", "Molding"],
    objectives: ["Draw pictures", "Use colors", "Create objects"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
];

// ============================================
// PRIMARY P2 (Primary Two) - Thematic Curriculum
// ============================================

export const P2_ALL_SUBJECTS: NSDCTopic[] = [
  // Language Activities P2
  {
    id: "p2-lang-t1-1",
    subject: "Language Activities",
    class_level: 2,
    level: "primary",
    term: 1,
    topic: "Oral Language",
    subtopics: ["Story telling", "Role play", "Conversation"],
    objectives: ["Tell simple stories", "Act out roles", "Have conversations"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "p2-lang-t1-2",
    subject: "Language Activities",
    class_level: 2,
    level: "primary",
    term: 1,
    topic: "Reading",
    subtopics: ["Phonics", "Word building", "Comprehension"],
    objectives: ["Blend sounds", "Read words", "Understand stories"],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p2-lang-t1-3",
    subject: "Language Activities",
    class_level: 2,
    level: "primary",
    term: 1,
    topic: "Writing",
    subtopics: ["Letter formation", "Sentence writing", "Punctuation"],
    objectives: ["Write letters", "Write sentences", "Use punctuation"],
    weeks: 3,
    competency_focus: "developing",
  },
  // Mathematical Activities P2
  {
    id: "p2-math-t1-1",
    subject: "Mathematical Activities",
    class_level: 2,
    level: "primary",
    term: 1,
    topic: "Numbers 1-20",
    subtopics: ["Counting", "Addition", "Subtraction"],
    objectives: ["Count to 20", "Add within 10", "Subtract within 10"],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p2-math-t1-2",
    subject: "Mathematical Activities",
    class_level: 2,
    level: "primary",
    term: 1,
    topic: "Money",
    subtopics: ["Recognizing coins", "Making amounts", "Shopping"],
    objectives: ["Know coins", "Make amounts", "Practice shopping"],
    weeks: 2,
    competency_focus: "developing",
    cross_cutting_theme: ["entrepreneurship"],
  },
  // Environmental Activities P2
  {
    id: "p2-env-t1-1",
    subject: "Environmental Activities",
    class_level: 2,
    level: "primary",
    term: 1,
    topic: "Animals",
    subtopics: ["Farm animals", "Wild animals", "Animal care"],
    objectives: ["Identify animals", "Know animal homes", "Care for animals"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "p2-env-t1-2",
    subject: "Environmental Activities",
    class_level: 2,
    level: "primary",
    term: 1,
    topic: "Plants",
    subtopics: ["Parts of plants", "Growing plants", "Uses of plants"],
    objectives: ["Know plant parts", "Plant seeds", "Use plants"],
    weeks: 2,
    competency_focus: "developing",
    cross_cutting_theme: ["climate"],
  },
];

// ============================================
// PRIMARY P3 (Primary Three) - Thematic Curriculum
// ============================================

export const P3_ALL_SUBJECTS: NSDCTopic[] = [
  // Language Activities P3
  {
    id: "p3-lang-t1-1",
    subject: "Language Activities",
    class_level: 3,
    level: "primary",
    term: 1,
    topic: "Reading Comprehension",
    subtopics: ["Main idea", "Details", "Sequence"],
    objectives: ["Find main idea", "Recall details", "Order events"],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p3-lang-t1-2",
    subject: "Language Activities",
    class_level: 3,
    level: "primary",
    term: 1,
    topic: "Creative Writing",
    subtopics: ["Paragraph writing", "Descriptions", "Story writing"],
    objectives: ["Write paragraphs", "Describe things", "Write stories"],
    weeks: 3,
    competency_focus: "developing",
  },
  // Mathematical Activities P3
  {
    id: "p3-math-t1-1",
    subject: "Mathematical Activities",
    class_level: 3,
    level: "primary",
    term: 1,
    topic: "Numbers to 100",
    subtopics: ["Place value", "Addition", "Subtraction"],
    objectives: [
      "Know place value",
      "Add 2-digit numbers",
      "Subtract 2-digit numbers",
    ],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p3-math-t1-2",
    subject: "Mathematical Activities",
    class_level: 3,
    level: "primary",
    term: 1,
    topic: "Multiplication",
    subtopics: ["Repeated addition", "Multiplication tables", "Word problems"],
    objectives: [
      "Understand multiplication",
      "Know 2,5,10 tables",
      "Solve problems",
    ],
    weeks: 3,
    competency_focus: "developing",
  },
  // Environmental Activities P3
  {
    id: "p3-env-t1-1",
    subject: "Environmental Activities",
    class_level: 3,
    level: "primary",
    term: 1,
    topic: "Weather and Climate",
    subtopics: ["Types of weather", "Seasons", "Climate change"],
    objectives: ["Observe weather", "Know seasons", "Understand climate"],
    weeks: 2,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "p3-env-t1-2",
    subject: "Environmental Activities",
    class_level: 3,
    level: "primary",
    term: 1,
    topic: "Our Community",
    subtopics: ["Community helpers", "Services", "Being a good citizen"],
    objectives: ["Know helpers", "Understand services", "Be a good citizen"],
    weeks: 2,
    competency_focus: "developing",
    cross_cutting_theme: ["community"],
  },
];

// ============================================
// PRIMARY P4 (Primary Four) - Subject-Based
// ============================================

export const P4_ALL_SUBJECTS: NSDCTopic[] = [
  // English P4
  {
    id: "p4-eng-t1-1",
    subject: "English",
    class_level: 4,
    level: "primary",
    term: 1,
    topic: "Reading",
    subtopics: ["Comprehension", "Vocabulary", "Summarizing"],
    objectives: ["Understand texts", "Build vocabulary", "Summarize passages"],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p4-eng-t1-2",
    subject: "English",
    class_level: 4,
    level: "primary",
    term: 1,
    topic: "Writing",
    subtopics: ["Paragraphs", "Letters", "Creative writing"],
    objectives: ["Write paragraphs", "Write letters", "Write creatively"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "p4-eng-t1-3",
    subject: "English",
    class_level: 4,
    level: "primary",
    term: 1,
    topic: "Grammar",
    subtopics: ["Verbs", "Tenses", "Punctuation"],
    objectives: ["Use verbs correctly", "Know tenses", "Apply punctuation"],
    weeks: 2,
    competency_focus: "mastered",
  },
  // Mathematics P4
  {
    id: "p4-math-t1-1",
    subject: "Mathematics",
    class_level: 4,
    level: "primary",
    term: 1,
    topic: "Whole Numbers",
    subtopics: ["Place value", "Rounding", "Operations"],
    objectives: [
      "Understand place value",
      "Round numbers",
      "Perform operations",
    ],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p4-math-t1-2",
    subject: "Mathematics",
    class_level: 4,
    level: "primary",
    term: 1,
    topic: "Fractions",
    subtopics: ["Types of fractions", "Operations", "Word problems"],
    objectives: [
      "Understand fractions",
      "Add/subtract fractions",
      "Solve problems",
    ],
    weeks: 3,
    competency_focus: "developing",
  },
  // Science P4
  {
    id: "p4-sci-t1-1",
    subject: "Science",
    class_level: 4,
    level: "primary",
    term: 1,
    topic: "Living Things",
    subtopics: ["Plants", "Animals", "Food chains"],
    objectives: [
      "Understand living things",
      "Know plants and animals",
      "Understand food chains",
    ],
    weeks: 3,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["environment"],
  },
  {
    id: "p4-sci-t1-2",
    subject: "Science",
    class_level: 4,
    level: "primary",
    term: 1,
    topic: "Matter",
    subtopics: ["States of matter", "Properties", "Changes"],
    objectives: [
      "Know states of matter",
      "Understand properties",
      "Observe changes",
    ],
    weeks: 3,
    competency_focus: "developing",
  },
  // Social Studies P4
  {
    id: "p4-soc-t1-1",
    subject: "Social Studies",
    class_level: 4,
    level: "primary",
    term: 1,
    topic: "Our District",
    subtopics: ["Location", "Resources", "Culture"],
    objectives: ["Know our district", "Use resources", "Preserve culture"],
    weeks: 3,
    competency_focus: "demonstrates",
  },
];

// ============================================
// PRIMARY P5 (Primary Five) - Subject-Based
// ============================================

export const P5_ALL_SUBJECTS: NSDCTopic[] = [
  // English P5
  {
    id: "p5-eng-t1-1",
    subject: "English",
    class_level: 5,
    level: "primary",
    term: 1,
    topic: "Comprehension",
    subtopics: ["Main idea", "Inference", "Critical reading"],
    objectives: ["Find main idea", "Make inferences", "Read critically"],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p5-eng-t1-2",
    subject: "English",
    class_level: 5,
    level: "primary",
    term: 1,
    topic: "Composition",
    subtopics: ["Essay writing", "Descriptive writing", "Narrative writing"],
    objectives: ["Write essays", "Write descriptions", "Write narratives"],
    weeks: 3,
    competency_focus: "developing",
  },
  // Mathematics P5
  {
    id: "p5-math-t1-1",
    subject: "Mathematics",
    class_level: 5,
    level: "primary",
    term: 1,
    topic: "Decimals",
    subtopics: ["Place value", "Operations", "Word problems"],
    objectives: ["Understand decimals", "Perform operations", "Solve problems"],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p5-math-t1-2",
    subject: "Mathematics",
    class_level: 5,
    level: "primary",
    term: 1,
    topic: "Percentages",
    subtopics: ["Converting", "Calculations", "Applications"],
    objectives: [
      "Convert fractions",
      "Calculate percentages",
      "Apply to problems",
    ],
    weeks: 3,
    competency_focus: "developing",
    cross_cutting_theme: ["entrepreneurship"],
  },
  // Science P5
  {
    id: "p5-sci-t1-1",
    subject: "Science",
    class_level: 5,
    level: "primary",
    term: 1,
    topic: "Energy",
    subtopics: ["Forms of energy", "Sources", "Conservation"],
    objectives: ["Know forms of energy", "Identify sources", "Conserve energy"],
    weeks: 3,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "p5-sci-t1-2",
    subject: "Science",
    class_level: 5,
    level: "primary",
    term: 1,
    topic: "Health",
    subtopics: ["Nutrition", "Disease prevention", "Sanitation"],
    objectives: [
      "Understand nutrition",
      "Prevent disease",
      "Maintain sanitation",
    ],
    weeks: 3,
    competency_focus: "developing",
    cross_cutting_theme: ["health"],
  },
];

// ============================================
// PRIMARY P6 (Primary Six) - Subject-Based
// ============================================

export const P6_ALL_SUBJECTS: NSDCTopic[] = [
  // English P6
  {
    id: "p6-eng-t1-1",
    subject: "English",
    class_level: 6,
    level: "primary",
    term: 1,
    topic: "Literature",
    subtopics: ["Poetry", "Short stories", "Drama"],
    objectives: ["Analyze poems", "Understand stories", "Appreciate drama"],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p6-eng-t1-2",
    subject: "English",
    class_level: 6,
    level: "primary",
    term: 1,
    topic: "Functional Writing",
    subtopics: ["Letters", "Reports", "Summaries"],
    objectives: ["Write formal letters", "Write reports", "Write summaries"],
    weeks: 3,
    competency_focus: "mastered",
  },
  // Mathematics P6
  {
    id: "p6-math-t1-1",
    subject: "Mathematics",
    class_level: 6,
    level: "primary",
    term: 1,
    topic: "Algebra",
    subtopics: ["Expressions", "Equations", "Word problems"],
    objectives: ["Form expressions", "Solve equations", "Apply to problems"],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p6-math-t1-2",
    subject: "Mathematics",
    class_level: 6,
    level: "primary",
    term: 1,
    topic: "Geometry",
    subtopics: ["Angles", "Lines", "Constructions"],
    objectives: ["Measure angles", "Identify lines", "Make constructions"],
    weeks: 3,
    competency_focus: "developing",
  },
  // Science P6
  {
    id: "p6-sci-t1-1",
    subject: "Science",
    class_level: 6,
    level: "primary",
    term: 1,
    topic: "Physics",
    subtopics: ["Force", "Motion", "Machines"],
    objectives: ["Understand force", "Know motion", "Use simple machines"],
    weeks: 3,
    competency_focus: "demonstrates",
  },
  {
    id: "p6-sci-t1-2",
    subject: "Science",
    class_level: 6,
    level: "primary",
    term: 1,
    topic: "Chemistry",
    subtopics: ["Elements", "Compounds", "Mixtures"],
    objectives: ["Know elements", "Understand compounds", "Separate mixtures"],
    weeks: 3,
    competency_focus: "developing",
  },
];

// ============================================
// PRIMARY P7 (Primary Seven) - Revision Year
// ============================================

export const P7_ALL_SUBJECTS: NSDCTopic[] = [
  // English P7
  {
    id: "p7-eng-t1-1",
    subject: "English",
    class_level: 7,
    level: "primary",
    term: 1,
    topic: "Revision of Grammar",
    subtopics: ["All grammar topics", "Common errors", "Practice"],
    objectives: ["Review grammar", "Fix errors", "Practice extensively"],
    weeks: 3,
    competency_focus: "mastered",
  },
  {
    id: "p7-eng-t1-2",
    subject: "English",
    class_level: 7,
    level: "primary",
    term: 1,
    topic: "Composition Revision",
    subtopics: ["All essay types", "Structure", "Practice"],
    objectives: ["Master essay types", "Improve structure", "Write well"],
    weeks: 3,
    competency_focus: "mastered",
  },
  // Mathematics P7
  {
    id: "p7-math-t1-1",
    subject: "Mathematics",
    class_level: 7,
    level: "primary",
    term: 1,
    topic: "Number Work Revision",
    subtopics: ["All operations", "Fractions", "Decimals", "Percentages"],
    objectives: ["Master all operations", "Handle all number types"],
    weeks: 3,
    competency_focus: "mastered",
  },
  {
    id: "p7-math-t1-2",
    subject: "Mathematics",
    class_level: 7,
    level: "primary",
    term: 1,
    topic: "Revision of All Topics",
    subtopics: ["Algebra", "Geometry", "Measurements", "Statistics"],
    objectives: [
      "Review all topics",
      "Practice past papers",
      "Prepare for exams",
    ],
    weeks: 4,
    competency_focus: "mastered",
  },
  // Science P7
  {
    id: "p7-sci-t1-1",
    subject: "Science",
    class_level: 7,
    level: "primary",
    term: 1,
    topic: "Integrated Science Revision",
    subtopics: ["Biology", "Chemistry", "Physics"],
    objectives: ["Review all sciences", "Understand integrated concepts"],
    weeks: 4,
    competency_focus: "mastered",
  },
];

// ============================================
// EXPORT ALL PRIMARY TOPICS
// ============================================

export const PRIMARY_TOPICS = [
  ...P1_ALL_SUBJECTS,
  ...P2_ALL_SUBJECTS,
  ...P3_ALL_SUBJECTS,
  ...P4_ALL_SUBJECTS,
  ...P5_ALL_SUBJECTS,
  ...P6_ALL_SUBJECTS,
  ...P7_ALL_SUBJECTS,
];

export const getPrimaryTopics = (
  classLevel: number,
  subject: string,
): NSDCTopic[] => {
  const levelMap: Record<number, NSDCTopic[]> = {
    1: P1_ALL_SUBJECTS,
    2: P2_ALL_SUBJECTS,
    3: P3_ALL_SUBJECTS,
    4: P4_ALL_SUBJECTS,
    5: P5_ALL_SUBJECTS,
    6: P6_ALL_SUBJECTS,
    7: P7_ALL_SUBJECTS,
  };
  const topics = levelMap[classLevel] || [];
  return topics.filter(
    (t) => t.subject.toLowerCase() === subject.toLowerCase(),
  );
};

// ============================================
// O-LEVEL S1 (Senior One) - All Subjects
// ============================================

export const S1_ALL_SUBJECTS: NSDCTopic[] = [
  // English S1
  {
    id: "eng-s1-t1-1",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Language",
    subtopics: ["Phonics", "Alphabet", "Word Building"],
    objectives: ["Identify sounds", "Form words", "Read simple text"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "eng-s1-t1-2",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Reading Comprehension",
    subtopics: ["Picture reading", "Silent reading", "Answering questions"],
    objectives: ["Extract meaning", "Identify main idea", "Answer questions"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "eng-s1-t1-3",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Creative Writing",
    subtopics: ["Writing sentences", "Paragraph structure", "Punctuation"],
    objectives: ["Construct sentences", "Organize ideas", "Use punctuation"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "eng-s1-t1-4",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Grammar - Parts of Speech",
    subtopics: ["Nouns", "Verbs", "Adjectives"],
    objectives: ["Identify parts of speech", "Use correctly in sentences"],
    weeks: 4,
    competency_focus: "developing",
  },
  {
    id: "eng-s1-t2-1",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Functional Writing",
    subtopics: ["Letters", "Emails", "Messages"],
    objectives: ["Write formal letters", "Compose emails", "Send messages"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "eng-s1-t2-2",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Poetry Appreciation",
    subtopics: ["Reading poetry", "Figurative language", "Analysis"],
    objectives: [
      "Analyze poems",
      "Identify metaphors",
      "Appreciate literary devices",
    ],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "eng-s1-t3-1",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Novel Study",
    subtopics: ["Plot Development", "Characters", "Themes"],
    objectives: ["Summarize plot", "Analyze characters", "Identify themes"],
    weeks: 1,
    competency_focus: "extended",
  },

  // Mathematics S1
  {
    id: "math-s1-t1-1",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Number Concepts",
    subtopics: ["Whole numbers", "Place value", "Operations"],
    objectives: [
      "Read and write numbers",
      "Understand place value",
      "Perform operations",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "math-s1-t1-2",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Fractions",
    subtopics: ["Proper fractions", "Equivalent fractions", "Operations"],
    objectives: [
      "Identify fractions",
      "Compare fractions",
      "Add/subtract fractions",
    ],
    weeks: 2,
    competency_focus: "developing",
  },
  {
    id: "math-s1-t1-3",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Decimals",
    subtopics: ["Decimal notation", "Place value", "Operations"],
    objectives: ["Convert fractions to decimals", "Perform decimal operations"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "math-s1-t2-1",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Measurements",
    subtopics: ["Length", "Mass", "Volume"],
    objectives: ["Measure accurately", "Convert units", "Solve real problems"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "math-s1-t2-2",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Geometry - Lines & Angles",
    subtopics: ["Lines", "Angles", "Triangles"],
    objectives: [
      "Identify geometric terms",
      "Measure angles",
      "Classify shapes",
    ],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "math-s1-t3-1",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Statistics",
    subtopics: ["Data collection", "Representation", "Interpretation"],
    objectives: ["Collect data", "Draw charts", "Interpret information"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["community"],
  },

  // Biology S1
  {
    id: "bio-s1-t1-1",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Biology",
    subtopics: ["What is biology?", "Branches", "Importance"],
    objectives: ["Define biology", "List branches", "Explain importance"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "bio-s1-t1-2",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Living Things",
    subtopics: ["Characteristics", "Classification", "Organization"],
    objectives: [
      "Identify characteristics",
      "Classify organisms",
      "Understand levels",
    ],
    weeks: 2,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "bio-s1-t1-3",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Cell Structure",
    subtopics: ["Cell theory", "Plant vs Animal cells", "Microscope use"],
    objectives: [
      "Explain cell theory",
      "Differentiate cells",
      "Use microscope",
    ],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "bio-s1-t2-1",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Nutrition",
    subtopics: ["Food groups", "Balanced diet", "Digestion"],
    objectives: ["Identify food groups", "Plan diet", "Explain digestion"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["health"],
  },
  {
    id: "bio-s1-t2-2",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Health & Hygiene",
    subtopics: ["Personal hygiene", "Common diseases", "Prevention"],
    objectives: ["Practice hygiene", "Identify diseases", "Apply prevention"],
    weeks: 2,
    competency_focus: "extended",
    cross_cutting_theme: ["health"],
  },
  {
    id: "bio-s1-t3-1",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Ecosystems",
    subtopics: ["Energy flow", "Food chains", "Environmental conservation"],
    objectives: [
      "Analyze energy flow",
      "Create food chains",
      "Promote conservation",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["climate"],
  },

  // Chemistry S1
  {
    id: "chem-s1-t1-1",
    subject: "Chemistry",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Chemistry",
    subtopics: ["What is chemistry?", "Scientific method", "Lab safety"],
    objectives: [
      "Define chemistry",
      "Apply scientific method",
      "Ensure safety",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "chem-s1-t1-2",
    subject: "Chemistry",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Matter",
    subtopics: ["States of matter", "Physical changes", "Chemical changes"],
    objectives: [
      "Describe states",
      "Differentiate changes",
      "Explain processes",
    ],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "chem-s1-t1-3",
    subject: "Chemistry",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Atoms & Elements",
    subtopics: ["Atomic structure", "Elements", "Periodic table basics"],
    objectives: ["Describe atoms", "Identify elements", "Use periodic table"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "chem-s1-t2-1",
    subject: "Chemistry",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Compounds & Mixtures",
    subtopics: ["Formation", "Separation techniques", "Properties"],
    objectives: ["Form compounds", "Separate mixtures", "Compare properties"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "chem-s1-t3-1",
    subject: "Chemistry",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Acids, Bases & Salts",
    subtopics: ["Properties", "Indicators", "Neutralization"],
    objectives: [
      "Identify acids/bases",
      "Use indicators",
      "Explain neutralization",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Physics S1
  {
    id: "phy-s1-t1-1",
    subject: "Physics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Physics",
    subtopics: ["What is physics?", "Measurement", "Scientific methods"],
    objectives: ["Define physics", "Make measurements", "Apply methods"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "phy-s1-t1-2",
    subject: "Physics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Motion",
    subtopics: ["Speed", "Velocity", "Acceleration"],
    objectives: [
      "Calculate speed",
      "Distinguish velocity",
      "Explain acceleration",
    ],
    weeks: 2,
    competency_focus: "developing",
  },
  {
    id: "phy-s1-t1-3",
    subject: "Physics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Forces",
    subtopics: ["Types of forces", "Effects", "Newton's laws intro"],
    objectives: ["Identify forces", "Explain effects", "Apply laws"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "phy-s1-t2-1",
    subject: "Physics",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Energy",
    subtopics: ["Forms", "Transformation", "Conservation"],
    objectives: ["Identify forms", "Transform energy", "Apply conservation"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "phy-s1-t3-1",
    subject: "Physics",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Waves",
    subtopics: ["Types", "Properties", "Sound & Light basics"],
    objectives: [
      "Classify waves",
      "Explain properties",
      "Analyze wave behavior",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Geography S1
  {
    id: "geo-s1-t1-1",
    subject: "Geography",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Geography",
    subtopics: ["Definition", "Branches", "Importance"],
    objectives: ["Define geography", "List branches", "Explain relevance"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "geo-s1-t1-2",
    subject: "Geography",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Map Reading",
    subtopics: ["Map types", "Symbols", "Scale"],
    objectives: ["Read maps", "Interpret symbols", "Use scale"],
    weeks: 2,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "geo-s1-t1-3",
    subject: "Geography",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Weather & Climate",
    subtopics: ["Elements", "Factors", "Climate zones"],
    objectives: ["Measure weather", "Analyze factors", "Classify climate"],
    weeks: 3,
    competency_focus: "developing",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "geo-s1-t2-1",
    subject: "Geography",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Rocks & Minerals",
    subtopics: ["Types", "Formation", "Economic importance"],
    objectives: ["Classify rocks", "Explain formation", "Identify uses"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["entrepreneurship"],
  },
  {
    id: "geo-s1-t3-1",
    subject: "Geography",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Population",
    subtopics: ["Distribution", "Migration", "Urbanization"],
    objectives: [
      "Analyze distribution",
      "Explain migration",
      "Evaluate urbanization",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["community"],
  },

  // History S1
  {
    id: "his-s1-t1-1",
    subject: "History",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to History",
    subtopics: ["Definition", "Sources", "Periodization"],
    objectives: ["Define history", "Collect sources", "Apply periodization"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "his-s1-t1-2",
    subject: "History",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Pre-colonial Uganda",
    subtopics: ["Kingdoms", "Trade routes", "Society"],
    objectives: ["Describe kingdoms", "Analyze trade", "Explain society"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "his-s1-t1-3",
    subject: "History",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Arrival of Explorers",
    subtopics: ["European explorers", "Motives", "Impact"],
    objectives: ["Identify explorers", "Explain motives", "Assess impact"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "his-s1-t2-1",
    subject: "History",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Colonial Period",
    subtopics: [
      "British administration",
      "Resistance movements",
      "Economic changes",
    ],
    objectives: [
      "Analyze administration",
      "Document resistance",
      "Evaluate changes",
    ],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["gender"],
  },
  {
    id: "his-s1-t3-1",
    subject: "History",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Independence & Nation Building",
    subtopics: [
      "Independence struggle",
      "Post-independence challenges",
      "Regional cooperation",
    ],
    objectives: [
      "Analyze struggle",
      "Evaluate challenges",
      "Explain cooperation",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["peace"],
  },

  // Computer Studies S1
  {
    id: "ict-s1-t1-1",
    subject: "Computer Studies",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to ICT",
    subtopics: ["Computer systems", "Input/Output devices", "Storage"],
    objectives: ["Identify components", "Explain functions", "Use storage"],
    weeks: 1,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "ict-s1-t1-2",
    subject: "Computer Studies",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Operating Systems",
    subtopics: ["Windows basics", "File management", "Settings"],
    objectives: ["Navigate OS", "Manage files", "Configure settings"],
    weeks: 2,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "ict-s1-t1-3",
    subject: "Computer Studies",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Word Processing",
    subtopics: ["Document creation", "Formatting", "Printing"],
    objectives: ["Create documents", "Apply formatting", "Print effectively"],
    weeks: 3,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "ict-s1-t2-1",
    subject: "Computer Studies",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Spreadsheets",
    subtopics: ["Formulas", "Functions", "Charts"],
    objectives: ["Use formulas", "Apply functions", "Create charts"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["ict", "entrepreneurship"],
  },
  {
    id: "ict-s1-t3-1",
    subject: "Computer Studies",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Internet & Email",
    subtopics: ["Browser use", "Email etiquette", "Online safety"],
    objectives: ["Use browser", "Compose emails", "Stay safe online"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["ict"],
  },

  // Entrepreneurship S1
  {
    id: "ent-s1-t1-1",
    subject: "Entrepreneurship",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Entrepreneurship",
    subtopics: ["Definitions", "Qualities", "Opportunities"],
    objectives: [
      "Define entrepreneurship",
      "Identify qualities",
      "Spot opportunities",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["entrepreneurship"],
  },
  {
    id: "ent-s1-t1-2",
    subject: "Entrepreneurship",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Business Ideas",
    subtopics: ["Idea generation", "Feasibility", "Market research"],
    objectives: ["Generate ideas", "Assess feasibility", "Research markets"],
    weeks: 2,
    competency_focus: "developing",
    cross_cutting_theme: ["entrepreneurship"],
  },
  {
    id: "ent-s1-t1-3",
    subject: "Entrepreneurship",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Business Plan Basics",
    subtopics: ["Structure", "Components", "Presentation"],
    objectives: ["Structure plans", "Identify components", "Present ideas"],
    weeks: 3,
    competency_focus: "developing",
    cross_cutting_theme: ["entrepreneurship"],
  },
  {
    id: "ent-s1-t2-1",
    subject: "Entrepreneurship",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Record Keeping",
    subtopics: ["Importance", "Books of accounts", "Basics"],
    objectives: [
      "Explain importance",
      "Maintain records",
      "Use basic accounting",
    ],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["entrepreneurship"],
  },
  {
    id: "ent-s1-t3-1",
    subject: "Entrepreneurship",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Marketing",
    subtopics: ["Marketing mix", "Promotion", "Customer relations"],
    objectives: [
      "Apply marketing mix",
      "Promote products",
      "Build customer relations",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["entrepreneurship"],
  },

  // Religious Education S1
  {
    id: "re-s1-t1-1",
    subject: "Religious Education",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Religion",
    subtopics: ["What is religion?", "World religions", "Importance"],
    objectives: ["Define religion", "Compare religions", "Explain importance"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "re-s1-t1-2",
    subject: "Religious Education",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Bible/ Quran Basics",
    subtopics: ["Scripture overview", "Key teachings", "Application"],
    objectives: [
      "Summarize scripture",
      "Identify teachings",
      "Apply principles",
    ],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "re-s1-t2-1",
    subject: "Religious Education",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Moral Values",
    subtopics: ["Honesty", "Respect", "Service"],
    objectives: ["Practice honesty", "Show respect", "Serve others"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["peace"],
  },
  {
    id: "re-s1-t3-1",
    subject: "Religious Education",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Community Service",
    subtopics: ["Help at school", "Help at home", "Help in community"],
    objectives: ["Identify ways to help", "Plan service", "Reflect on impact"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["community"],
  },

  // Physical Education S1
  {
    id: "pe-s1-t1-1",
    subject: "Physical Education",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Health & Fitness",
    subtopics: ["Components of fitness", "Exercise", "Nutrition for sports"],
    objectives: ["Define fitness", "Plan exercises", "Apply nutrition"],
    weeks: 1,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["health"],
  },
  {
    id: "pe-s1-t1-2",
    subject: "Physical Education",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Ball Games",
    subtopics: ["Football basics", "Netball basics", "Volleyball basics"],
    objectives: ["Play football", "Play netball", "Play volleyball"],
    weeks: 2,
    competency_focus: "mastered",
    cross_cutting_theme: ["health"],
  },
  {
    id: "pe-s1-t2-1",
    subject: "Physical Education",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Athletics",
    subtopics: ["Running", "Jumping", "Throwing"],
    objectives: ["Run correctly", "Jump safely", "Throw effectively"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["health"],
  },
];

// ============================================
// O-LEVEL S2 (Senior Two)
// ============================================

export const S2_ALL_SUBJECTS: NSDCTopic[] = [
  // English S2
  {
    id: "eng-s2-t1-1",
    subject: "English",
    class_level: 2,
    level: "o-level",
    term: 1,
    topic: "Advanced Reading",
    subtopics: ["Critical reading", "Inference", "Analysis"],
    objectives: ["Read critically", "Make inferences", "Analyze text"],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "eng-s2-t1-2",
    subject: "English",
    class_level: 2,
    level: "o-level",
    term: 1,
    topic: "Essay Writing",
    subtopics: ["Essay types", "Structure", "Flow"],
    objectives: ["Write essays", "Organize ideas", "Maintain flow"],
    weeks: 2,
    competency_focus: "mastered",
  },
  {
    id: "eng-s2-t2-1",
    subject: "English",
    class_level: 2,
    level: "o-level",
    term: 2,
    topic: "Grammar - Advanced",
    subtopics: ["Tense", "Voice", "Subject-verb agreement"],
    objectives: ["Master tenses", "Use voice correctly", "Apply agreement"],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "eng-s2-t3-1",
    subject: "English",
    class_level: 2,
    level: "o-level",
    term: 3,
    topic: "Literature",
    subtopics: ["Prose", "Poetry", "Drama"],
    objectives: [
      "Analyze literature forms",
      "Appreciate techniques",
      "Write critically",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Mathematics S2
  {
    id: "math-s2-t1-1",
    subject: "Mathematics",
    class_level: 2,
    level: "o-level",
    term: 1,
    topic: "Algebra - Expressions",
    subtopics: ["Simplification", "Factorisation", "Expansion"],
    objectives: [
      "Simplify expressions",
      "Factorize equations",
      "Expand brackets",
    ],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "math-s2-t1-2",
    subject: "Mathematics",
    class_level: 2,
    level: "o-level",
    term: 1,
    topic: "Linear Equations",
    subtopics: ["Methods", "Word problems", "Applications"],
    objectives: [
      "Solve linear equations",
      "Apply to problems",
      "Use in real life",
    ],
    weeks: 2,
    competency_focus: "mastered",
  },
  {
    id: "math-s2-t2-1",
    subject: "Mathematics",
    class_level: 2,
    level: "o-level",
    term: 2,
    topic: "Geometry - Angles & Triangles",
    subtopics: ["Angle properties", "Triangle theorems", "Proofs"],
    objectives: [
      "Apply angle properties",
      "Use triangle theorems",
      "Write proofs",
    ],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "math-s2-t3-1",
    subject: "Mathematics",
    class_level: 2,
    level: "o-level",
    term: 3,
    topic: "Probability",
    subtopics: [
      "Basic probability",
      "Mutually exclusive",
      "Independent events",
    ],
    objectives: ["Calculate probability", "Apply rules", "Solve problems"],
    weeks: 1,
    competency_focus: "extended",
  },

  // Add more S2 subjects as needed...
];

// Combine all O-Level (S1-S4)
export const O_LEVEL_TOPICS = [...S1_ALL_SUBJECTS, ...S2_ALL_SUBJECTS];

// Empty placeholders for S3-S4 and A-Level (S5-S6)
export const S3_ALL_SUBJECTS: NSDCTopic[] = [
  // English S3
  {
    id: "eng-s3-t1-1",
    subject: "English",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Advanced Composition",
    subtopics: ["Descriptive", "Narrative", "Expository"],
    objectives: [
      "Write descriptive essays",
      "Write narrative essays",
      "Write expository pieces",
    ],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "eng-s3-t1-2",
    subject: "English",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Literature - Prose",
    subtopics: ["Novel analysis", "Character analysis", "Theme identification"],
    objectives: ["Analyze novels", "Evaluate characters", "Identify themes"],
    weeks: 2,
    competency_focus: "extended",
  },
  {
    id: "eng-s3-t2-1",
    subject: "English",
    class_level: 3,
    level: "o-level",
    term: 2,
    topic: "Grammar - Advanced",
    subtopics: ["Conditional", "Relative clauses", "Phrasal verbs"],
    objectives: [
      "Use conditionals",
      "Apply relative clauses",
      "Master phrasal verbs",
    ],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "eng-s3-t3-1",
    subject: "English",
    class_level: 3,
    level: "o-level",
    term: 3,
    topic: "Summary & Comprehension",
    subtopics: ["Summary writing", "Comprehension skills", "Critical analysis"],
    objectives: ["Write summaries", "Analyze texts", "Think critically"],
    weeks: 1,
    competency_focus: "extended",
  },

  // Mathematics S3
  {
    id: "math-s3-t1-1",
    subject: "Mathematics",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Quadratic Equations",
    subtopics: ["Factorization", "Formula method", "Completing square"],
    objectives: ["Solve by factorizing", "Use formula", "Complete square"],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "math-s3-t1-2",
    subject: "Mathematics",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Simultaneous Equations",
    subtopics: ["Substitution", "Elimination", "Graphical"],
    objectives: [
      "Solve substitution",
      "Solve elimination",
      "Use graphical method",
    ],
    weeks: 2,
    competency_focus: "mastered",
  },
  {
    id: "math-s3-t2-1",
    subject: "Mathematics",
    class_level: 3,
    level: "o-level",
    term: 2,
    topic: "Trigonometry",
    subtopics: ["Ratios", "Identities", "Equations"],
    objectives: ["Use trig ratios", "Apply identities", "Solve trig equations"],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "math-s3-t3-1",
    subject: "Mathematics",
    class_level: 3,
    level: "o-level",
    term: 3,
    topic: "Statistics",
    subtopics: ["Mean, Median, Mode", "Variance", "Representation"],
    objectives: ["Calculate measures", "Analyze data", "Represent graphically"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["ict"],
  },

  // Biology S3
  {
    id: "bio-s3-t1-1",
    subject: "Biology",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Reproduction",
    subtopics: ["Plants", "Animals", "Human"],
    objectives: [
      "Explain reproduction",
      "Compare methods",
      "Understand human reproduction",
    ],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["health"],
  },
  {
    id: "bio-s3-t1-2",
    subject: "Biology",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Growth & Development",
    subtopics: ["Photosynthesis", "Respiration", "Gaseous exchange"],
    objectives: [
      "Explain photosynthesis",
      "Understand respiration",
      "Analyze gas exchange",
    ],
    weeks: 2,
    competency_focus: "extended",
  },
  {
    id: "bio-s3-t2-1",
    subject: "Biology",
    class_level: 3,
    level: "o-level",
    term: 2,
    topic: "Inheritance",
    subtopics: ["Genetics", "Variation", "Evolution"],
    objectives: [
      "Understand genetics",
      "Explain variation",
      "Apply evolution concepts",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Chemistry S3
  {
    id: "chem-s3-t1-1",
    subject: "Chemistry",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Chemical Reactions",
    subtopics: ["Types", "Rates", "Equilibrium"],
    objectives: ["Identify types", "Explain rates", "Understand equilibrium"],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "chem-s3-t2-1",
    subject: "Chemistry",
    class_level: 3,
    level: "o-level",
    term: 2,
    topic: "Organic Chemistry",
    subtopics: ["Hydrocarbons", "Alkanes", "Alkenes"],
    objectives: [
      "Identify hydrocarbons",
      "Name compounds",
      "Understand properties",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Physics S3
  {
    id: "phy-s3-t1-1",
    subject: "Physics",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Reflection",
    subtopics: ["Laws", "Mirrors", "Images"],
    objectives: ["Apply laws", "Use mirrors", "Analyze images"],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "phy-s3-t1-2",
    subject: "Physics",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Refraction",
    subtopics: ["Laws", "Lenses", "Optical devices"],
    objectives: ["Apply refraction laws", "Use lenses", "Understand devices"],
    weeks: 2,
    competency_focus: "mastered",
  },
  {
    id: "phy-s3-t2-1",
    subject: "Physics",
    class_level: 3,
    level: "o-level",
    term: 2,
    topic: "Electricity",
    subtopics: ["Circuits", "Ohms law", "Power"],
    objectives: ["Analyze circuits", "Apply Ohms law", "Calculate power"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["ict"],
  },

  // Geography S3
  {
    id: "geo-s3-t1-1",
    subject: "Geography",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Plate Tectonics",
    subtopics: ["Earth structure", "Movements", "Landforms"],
    objectives: [
      "Explain structure",
      "Understand movements",
      "Identify landforms",
    ],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "geo-s3-t1-2",
    subject: "Geography",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Weather & Climate",
    subtopics: ["Atmospheric circulation", "Climate zones", "Climate change"],
    objectives: [
      "Explain circulation",
      "Classify zones",
      "Analyze climate change",
    ],
    weeks: 2,
    competency_focus: "extended",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "geo-s3-t2-1",
    subject: "Geography",
    class_level: 3,
    level: "o-level",
    term: 2,
    topic: "Economic Geography",
    subtopics: ["Agriculture", "Industry", "Trade"],
    objectives: [
      "Analyze agriculture",
      "Understand industry",
      "Evaluate trade",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["entrepreneurship"],
  },

  // History S3
  {
    id: "his-s3-t1-1",
    subject: "History",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "East African History",
    subtopics: ["Buganda kingdom", "Trade routes", "Colonial impact"],
    objectives: ["Analyze Buganda", "Evaluate trade", "Assess impact"],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "his-s3-t1-2",
    subject: "History",
    class_level: 3,
    level: "o-level",
    term: 1,
    topic: "Pan-Africanism",
    subtopics: ["Movements", "Leaders", "Independence"],
    objectives: [
      "Understand movements",
      "Evaluate leaders",
      "Analyze independence",
    ],
    weeks: 2,
    competency_focus: "extended",
    cross_cutting_theme: ["peace"],
  },
  {
    id: "his-s3-t2-1",
    subject: "History",
    class_level: 3,
    level: "o-level",
    term: 2,
    topic: "World Wars",
    subtopics: ["WWI", "WWII", "Africa"],
    objectives: ["Analyze WWI", "Understand WWII", "Relate to Africa"],
    weeks: 1,
    competency_focus: "extended",
  },
];

export const S4_ALL_SUBJECTS: NSDCTopic[] = [
  // English S4 - Revision Year
  {
    id: "eng-s4-t1-1",
    subject: "English",
    class_level: 4,
    level: "o-level",
    term: 1,
    topic: "Revision - Paper 1",
    subtopics: ["Comprehension", "Summary", "Creative writing"],
    objectives: [
      "Practice comprehension",
      "Write summaries",
      "Improve creative writing",
    ],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "eng-s4-t1-2",
    subject: "English",
    class_level: 4,
    level: "o-level",
    term: 1,
    topic: "Revision - Literature",
    subtopics: ["Novels", "Plays", "Poetry"],
    objectives: ["Revise novels", "Analyze plays", "Appreciate poetry"],
    weeks: 2,
    competency_focus: "extended",
  },
  {
    id: "eng-s4-t2-1",
    subject: "English",
    class_level: 4,
    level: "o-level",
    term: 2,
    topic: "Exam Techniques",
    subtopics: ["Time management", "Past papers", "Marking schemes"],
    objectives: ["Manage time", "Practice past papers", "Understand marking"],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "eng-s4-t3-1",
    subject: "English",
    class_level: 4,
    level: "o-level",
    term: 3,
    topic: "Mock Exams & Review",
    subtopics: ["Mock paper 1", "Mock paper 2", "Feedback"],
    objectives: ["Complete mocks", "Review answers", "Improve scores"],
    weeks: 1,
    competency_focus: "extended",
  },

  // Mathematics S4
  {
    id: "math-s4-t1-1",
    subject: "Mathematics",
    class_level: 4,
    level: "o-level",
    term: 1,
    topic: "Revision - Numerical",
    subtopics: ["Number", "Algebra", "Geometry"],
    objectives: ["Revise number", "Practice algebra", "Review geometry"],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "math-s4-t1-2",
    subject: "Mathematics",
    class_level: 4,
    level: "o-level",
    term: 1,
    topic: "Revision - Statistics & Probability",
    subtopics: ["Data handling", "Probability rules", "Past paper analysis"],
    objectives: ["Handle data", "Apply probability", "Analyze papers"],
    weeks: 2,
    competency_focus: "extended",
  },
  {
    id: "math-s4-t2-1",
    subject: "Mathematics",
    class_level: 4,
    level: "o-level",
    term: 2,
    topic: "Mock Exams",
    subtopics: ["Paper 1", "Paper 2", "Solutions"],
    objectives: ["Attempt mocks", "Review solutions", "Score marks"],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "math-s4-t3-1",
    subject: "Mathematics",
    class_level: 4,
    level: "o-level",
    term: 3,
    topic: "Final Review",
    subtopics: ["Weak areas", "Past papers", "Exam tips"],
    objectives: ["Identify weak areas", "Practice papers", "Apply tips"],
    weeks: 1,
    competency_focus: "extended",
  },

  // Biology S4
  {
    id: "bio-s4-t1-1",
    subject: "Biology",
    class_level: 4,
    level: "o-level",
    term: 1,
    topic: "Revision - Paper 1",
    subtopics: ["Multiple choice", "Structured", "Essay"],
    objectives: ["Practice MCQ", "Answer structured", "Write essays"],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "bio-s4-t1-2",
    subject: "Biology",
    class_level: 4,
    level: "o-level",
    term: 1,
    topic: "Revision - Paper 2/3",
    subtopics: ["Homework", "Field work", "Records"],
    objectives: ["Complete homework", "Document fieldwork", "Keep records"],
    weeks: 2,
    competency_focus: "extended",
  },
  {
    id: "bio-s4-t2-1",
    subject: "Biology",
    class_level: 4,
    level: "o-level",
    term: 2,
    topic: "Mock Exams & Review",
    subtopics: ["Paper 1", "Paper 2", "Feedback"],
    objectives: ["Attempt mocks", "Review feedback", "Improve"],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "bio-s4-t3-1",
    subject: "Biology",
    class_level: 4,
    level: "o-level",
    term: 3,
    topic: "Final Prep",
    subtopics: ["Past papers", "Marking", "Confidence"],
    objectives: ["Practice papers", "Review marks", "Build confidence"],
    weeks: 1,
    competency_focus: "extended",
  },

  // Chemistry S4
  {
    id: "chem-s4-t1-1",
    subject: "Chemistry",
    class_level: 4,
    level: "o-level",
    term: 1,
    topic: "Revision - Organic",
    subtopics: ["Hydrocarbons", "Reactions", "Nomenclature"],
    objectives: [
      "Revise hydrocarbons",
      "Practice reactions",
      "Apply nomenclature",
    ],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "chem-s4-t2-1",
    subject: "Chemistry",
    class_level: 4,
    level: "o-level",
    term: 2,
    topic: "Mock Exams",
    subtopics: ["Paper 1", "Paper 2", "Practicals"],
    objectives: ["Attempt mocks", "Review papers", "Practice practicals"],
    weeks: 1,
    competency_focus: "extended",
  },

  // Physics S4
  {
    id: "phy-s4-t1-1",
    subject: "Physics",
    class_level: 4,
    level: "o-level",
    term: 1,
    topic: "Revision - Mechanics",
    subtopics: ["Motion", "Forces", "Energy"],
    objectives: ["Revise motion", "Understand forces", "Apply energy concepts"],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "phy-s4-t2-1",
    subject: "Physics",
    class_level: 4,
    level: "o-level",
    term: 2,
    topic: "Mock Exams",
    subtopics: ["Paper 1", "Paper 2", "Practicals"],
    objectives: ["Attempt mocks", "Review papers", "Practice practicals"],
    weeks: 1,
    competency_focus: "extended",
  },
];

// ============================================
// A-LEVEL S5 (Senior Five) - Advanced
// ============================================

export const S5_ALL_SUBJECTS: NSDCTopic[] = [
  // Biology A-Level S5
  {
    id: "bio-s5-t1-1",
    subject: "Biology",
    class_level: 5,
    level: "a-level",
    term: 1,
    topic: "Cell Biology",
    subtopics: ["Cell structure", "Cell division", "Cell metabolism"],
    objectives: [
      "Analyze cell structure",
      "Explain cell division",
      "Understand metabolism",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "bio-s5-t1-2",
    subject: "Biology",
    class_level: 5,
    level: "a-level",
    term: 1,
    topic: "Molecular Biology",
    subtopics: ["DNA", "RNA", "Protein synthesis"],
    objectives: [
      "Explain DNA structure",
      "Understand RNA",
      "Analyze protein synthesis",
    ],
    weeks: 2,
    competency_focus: "developing",
  },
  {
    id: "bio-s5-t2-1",
    subject: "Biology",
    class_level: 5,
    level: "a-level",
    term: 2,
    topic: "Genetics",
    subtopics: ["Mendelian genetics", "DNA technology", "Genetic engineering"],
    objectives: [
      "Apply Mendelian laws",
      "Understand DNA technology",
      "Analyze genetic engineering",
    ],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "bio-s5-t3-1",
    subject: "Biology",
    class_level: 5,
    level: "a-level",
    term: 3,
    topic: "Ecology",
    subtopics: ["Ecosystems", "Energy flow", "Conservation"],
    objectives: [
      "Analyze ecosystems",
      "Explain energy flow",
      "Promote conservation",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["climate"],
  },

  // Chemistry A-Level S5
  {
    id: "chem-s5-t1-1",
    subject: "Chemistry",
    class_level: 5,
    level: "a-level",
    term: 1,
    topic: "Physical Chemistry",
    subtopics: ["Atomic structure", "Chemical bonding", "Thermodynamics"],
    objectives: [
      "Understand atomic structure",
      "Explain bonding",
      "Apply thermodynamics",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "chem-s5-t1-2",
    subject: "Chemistry",
    class_level: 5,
    level: "a-level",
    term: 1,
    topic: "Inorganic Chemistry",
    subtopics: [
      "Periodic table",
      "Transition metals",
      "Coordination compounds",
    ],
    objectives: [
      "Analyze periodic trends",
      "Understand transition metals",
      "Explain coordination",
    ],
    weeks: 2,
    competency_focus: "developing",
  },
  {
    id: "chem-s5-t2-1",
    subject: "Chemistry",
    class_level: 5,
    level: "a-level",
    term: 2,
    topic: "Organic Chemistry",
    subtopics: ["Reaction mechanisms", "Stereochemistry", "Spectroscopy"],
    objectives: [
      "Understand mechanisms",
      "Analyze stereochemistry",
      "Apply spectroscopy",
    ],
    weeks: 1,
    competency_focus: "mastered",
  },

  // Physics A-Level S5
  {
    id: "phy-s5-t1-1",
    subject: "Physics",
    class_level: 5,
    level: "a-level",
    term: 1,
    topic: "Mechanics",
    subtopics: ["Kinematics", "Dynamics", "Work and energy"],
    objectives: ["Analyze motion", "Apply Newton laws", "Calculate work"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "phy-s5-t1-2",
    subject: "Physics",
    class_level: 5,
    level: "a-level",
    term: 1,
    topic: "Waves & Oscillations",
    subtopics: ["Simple harmonic motion", "Damping", "Resonance"],
    objectives: ["Understand SHM", "Analyze damping", "Apply resonance"],
    weeks: 2,
    competency_focus: "developing",
  },
  {
    id: "phy-s5-t2-1",
    subject: "Physics",
    class_level: 5,
    level: "a-level",
    term: 2,
    topic: "Electricity & Magnetism",
    subtopics: ["Electric fields", "Capacitance", "Electromagnetism"],
    objectives: [
      "Analyze fields",
      "Understand capacitance",
      "Apply electromagnetism",
    ],
    weeks: 1,
    competency_focus: "mastered",
  },

  // Mathematics A-Level S5
  {
    id: "math-s5-t1-1",
    subject: "Mathematics",
    class_level: 5,
    level: "a-level",
    term: 1,
    topic: "Calculus",
    subtopics: ["Differentiation", "Integration", "Differential equations"],
    objectives: [
      "Differentiate functions",
      "Integrate functions",
      "Solve differential equations",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "math-s5-t1-2",
    subject: "Mathematics",
    class_level: 5,
    level: "a-level",
    term: 1,
    topic: "Algebra",
    subtopics: ["Matrices", "Determinants", "Linear programming"],
    objectives: [
      "Use matrices",
      "Calculate determinants",
      "Apply linear programming",
    ],
    weeks: 2,
    competency_focus: "developing",
  },
  {
    id: "math-s5-t2-1",
    subject: "Mathematics",
    class_level: 5,
    level: "a-level",
    term: 2,
    topic: "Statistics & Probability",
    subtopics: ["Distributions", "Hypothesis testing", "Regression"],
    objectives: [
      "Analyze distributions",
      "Test hypotheses",
      "Apply regression",
    ],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },

  // Geography A-Level S5
  {
    id: "geo-s5-t1-1",
    subject: "Geography",
    class_level: 5,
    level: "a-level",
    term: 1,
    topic: "Geomorphology",
    subtopics: ["Earth processes", "Landforms", "Plate tectonics"],
    objectives: [
      "Analyze processes",
      "Identify landforms",
      "Understand tectonics",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "geo-s5-t2-1",
    subject: "Geography",
    class_level: 5,
    level: "a-level",
    term: 2,
    topic: "Climatology",
    subtopics: ["Atmospheric systems", "Climate change", "Weather patterns"],
    objectives: [
      "Analyze atmospheric systems",
      "Understand climate change",
      "Interpret weather",
    ],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["climate"],
  },

  // History A-Level S5
  {
    id: "his-s5-t1-1",
    subject: "History",
    class_level: 5,
    level: "a-level",
    term: 1,
    topic: "World History",
    subtopics: ["Imperialism", "World wars", "Cold war"],
    objectives: [
      "Analyze imperialism",
      "Understand world wars",
      "Evaluate cold war",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["peace"],
  },
  {
    id: "his-s5-t2-1",
    subject: "History",
    class_level: 5,
    level: "a-level",
    term: 2,
    topic: "African History",
    subtopics: [
      "Colonialism",
      "Independence movements",
      "Post-colonial Africa",
    ],
    objectives: [
      "Analyze colonialism",
      "Evaluate independence",
      "Understand post-colonial Africa",
    ],
    weeks: 1,
    competency_focus: "mastered",
  },
];

// ============================================
// A-LEVEL S6 (Senior Six) - Final Year
// ============================================

export const S6_ALL_SUBJECTS: NSDCTopic[] = [
  // Biology A-Level S6
  {
    id: "bio-s6-t1-1",
    subject: "Biology",
    class_level: 6,
    level: "a-level",
    term: 1,
    topic: "Human Physiology",
    subtopics: ["Circulation", "Respiration", "Excretion"],
    objectives: [
      "Analyze human systems",
      "Understand circulation",
      "Explain respiration",
    ],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["health"],
  },
  {
    id: "bio-s6-t2-1",
    subject: "Biology",
    class_level: 6,
    level: "a-level",
    term: 2,
    topic: "Evolution & Speciation",
    subtopics: ["Natural selection", "Adaptations", "Biodiversity"],
    objectives: [
      "Understand evolution",
      "Analyze adaptations",
      "Evaluate biodiversity",
    ],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "bio-s6-t3-1",
    subject: "Biology",
    class_level: 6,
    level: "a-level",
    term: 3,
    topic: "Revision & Mock Exams",
    subtopics: ["Past papers", "Practicals", "Exam technique"],
    objectives: [
      "Practice papers",
      "Master practicals",
      "Apply exam technique",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Chemistry A-Level S6
  {
    id: "chem-s6-t1-1",
    subject: "Chemistry",
    class_level: 6,
    level: "a-level",
    term: 1,
    topic: "Advanced Physical Chemistry",
    subtopics: ["Kinetics", "Equilibrium", "Electrochemistry"],
    objectives: [
      "Analyze kinetics",
      "Understand equilibrium",
      "Apply electrochemistry",
    ],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "chem-s6-t2-1",
    subject: "Chemistry",
    class_level: 6,
    level: "a-level",
    term: 2,
    topic: "Advanced Organic Chemistry",
    subtopics: ["Synthesis", "Mechanisms", "Spectroscopy"],
    objectives: ["Plan synthesis", "Analyze mechanisms", "Use spectroscopy"],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "chem-s6-t3-1",
    subject: "Chemistry",
    class_level: 6,
    level: "a-level",
    term: 3,
    topic: "Revision & Mock Exams",
    subtopics: ["Past papers", "Practicals", "Exam technique"],
    objectives: [
      "Practice papers",
      "Master practicals",
      "Apply exam technique",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Physics A-Level S6
  {
    id: "phy-s6-t1-1",
    subject: "Physics",
    class_level: 6,
    level: "a-level",
    term: 1,
    topic: "Modern Physics",
    subtopics: ["Relativity", "Quantum mechanics", "Nuclear physics"],
    objectives: [
      "Understand relativity",
      "Apply quantum concepts",
      "Analyze nuclear physics",
    ],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "phy-s6-t2-1",
    subject: "Physics",
    class_level: 6,
    level: "a-level",
    term: 2,
    topic: "Electronics",
    subtopics: ["Semiconductors", "Digital electronics", "Communication"],
    objectives: [
      "Analyze semiconductors",
      "Design digital circuits",
      "Understand communication systems",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "phy-s6-t3-1",
    subject: "Physics",
    class_level: 6,
    level: "a-level",
    term: 3,
    topic: "Revision & Mock Exams",
    subtopics: ["Past papers", "Practicals", "Exam technique"],
    objectives: [
      "Practice papers",
      "Master practicals",
      "Apply exam technique",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Mathematics A-Level S6
  {
    id: "math-s6-t1-1",
    subject: "Mathematics",
    class_level: 6,
    level: "a-level",
    term: 1,
    topic: "Advanced Calculus",
    subtopics: ["Series", "Taylor expansion", "Vector calculus"],
    objectives: [
      "Analyze series",
      "Apply Taylor expansion",
      "Use vector calculus",
    ],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "math-s6-t2-1",
    subject: "Mathematics",
    class_level: 6,
    level: "a-level",
    term: 2,
    topic: "Complex Numbers",
    subtopics: ["Operations", "Polar form", "De Moivre theorem"],
    objectives: [
      "Operate complex numbers",
      "Use polar form",
      "Apply De Moivre",
    ],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "math-s6-t3-1",
    subject: "Mathematics",
    class_level: 6,
    level: "a-level",
    term: 3,
    topic: "Revision & Mock Exams",
    subtopics: ["Past papers", "Problem solving", "Exam technique"],
    objectives: ["Practice papers", "Solve problems", "Apply exam technique"],
    weeks: 1,
    competency_focus: "extended",
  },
];

// Complete database
export const ALL_NCDC_TOPICS = [
  ...S1_ALL_SUBJECTS,
  ...S2_ALL_SUBJECTS,
  ...S3_ALL_SUBJECTS,
  ...S4_ALL_SUBJECTS,
  ...S5_ALL_SUBJECTS,
  ...S6_ALL_SUBJECTS,
];

// Helper functions
export function getTopicsBySubject(subject: string): NSDCTopic[] {
  return ALL_NCDC_TOPICS.filter((t) => t.subject === subject);
}

export function getTopicsByClass(
  subject: string,
  classLevel: number,
): NSDCTopic[] {
  return ALL_NCDC_TOPICS.filter(
    (t) => t.subject === subject && t.class_level === classLevel,
  );
}

export function getTopicsByTerm(
  subject: string,
  classLevel: number,
  term: number,
): NSDCTopic[] {
  return ALL_NCDC_TOPICS.filter(
    (t) =>
      t.subject === subject && t.class_level === classLevel && t.term === term,
  );
}

export function getTopicsByLevel(level: "o-level" | "a-level"): NSDCTopic[] {
  return ALL_NCDC_TOPICS.filter((t) => t.level === level);
}

export function getSubjectStats() {
  const stats: { [key: string]: number } = {};
  ALL_NCDC_TOPICS.forEach((t) => {
    stats[t.subject] = (stats[t.subject] || 0) + 1;
  });
  return Object.entries(stats).map(([subject, count]) => ({
    subject,
    topics: count,
  }));
}

// For database seed - generates syllabus records for all topics
export function generateSyllabusSeed(
  schoolId: string,
  classId: string,
  subjectId: string,
) {
  const topics = ALL_NCDC_TOPICS.filter(
    (t) =>
      t.subject === subjectId.split("-")[0] ||
      subjectId.includes(t.subject.toLowerCase()),
  );
  return topics.map((topic) => ({
    school_id: schoolId,
    class_id: classId,
    subject_id: subjectId,
    topic: topic.topic,
    subtopics: topic.subtopics,
    term: topic.term,
    weeks_covered: topic.weeks.toString(),
    competency_focus: topic.competency_focus,
    cross_cutting_theme: topic.cross_cutting_theme,
  }));
}
