// NCDC Uganda Complete Syllabus Database
// Based on NCDC 2025 Curriculum
// O-Level: S1-S4 (Lower Secondary)
// A-Level: S5-S6 (Advanced Secondary)

export interface NSDCTopic {
  id: string;
  subject: string;
  class_level: number; // 1-6 (S1-S6)
  level: "o-level" | "a-level";
  term: number; // 1-3
  topic: string;
  subtopics: string[];
  objectives: string[];
  weeks: number;
  competency_focus?: string;
  cross_cutting_theme?: string[];
}

// ============================================
// O-LEVEL S1 (Senior One) - All Subjects
// ============================================

export const S1_ALL_SUBJECTS: NSDCTopic[] = [
  // English S1
  {
    id: "eng-s1-t1-1",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Language",
    subtopics: ["Phonics", "Alphabet", "Word Building"],
    objectives: ["Identify sounds", "Form words", "Read simple text"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "eng-s1-t1-2",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Reading Comprehension",
    subtopics: ["Picture reading", "Silent reading", "Answering questions"],
    objectives: ["Extract meaning", "Identify main idea", "Answer questions"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "eng-s1-t1-3",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Creative Writing",
    subtopics: ["Writing sentences", "Paragraph structure", "Punctuation"],
    objectives: ["Construct sentences", "Organize ideas", "Use punctuation"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "eng-s1-t1-4",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Grammar - Parts of Speech",
    subtopics: ["Nouns", "Verbs", "Adjectives"],
    objectives: ["Identify parts of speech", "Use correctly in sentences"],
    weeks: 4,
    competency_focus: "developing",
  },
  {
    id: "eng-s1-t2-1",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Functional Writing",
    subtopics: ["Letters", "Emails", "Messages"],
    objectives: ["Write formal letters", "Compose emails", "Send messages"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "eng-s1-t2-2",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Poetry Appreciation",
    subtopics: ["Reading poetry", "Figurative language", "Analysis"],
    objectives: [
      "Analyze poems",
      "Identify metaphors",
      "Appreciate literary devices",
    ],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "eng-s1-t3-1",
    subject: "English",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Novel Study",
    subtopics: ["Plot Development", "Characters", "Themes"],
    objectives: ["Summarize plot", "Analyze characters", "Identify themes"],
    weeks: 1,
    competency_focus: "extended",
  },

  // Mathematics S1
  {
    id: "math-s1-t1-1",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Number Concepts",
    subtopics: ["Whole numbers", "Place value", "Operations"],
    objectives: [
      "Read and write numbers",
      "Understand place value",
      "Perform operations",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "math-s1-t1-2",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Fractions",
    subtopics: ["Proper fractions", "Equivalent fractions", "Operations"],
    objectives: [
      "Identify fractions",
      "Compare fractions",
      "Add/subtract fractions",
    ],
    weeks: 2,
    competency_focus: "developing",
  },
  {
    id: "math-s1-t1-3",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Decimals",
    subtopics: ["Decimal notation", "Place value", "Operations"],
    objectives: ["Convert fractions to decimals", "Perform decimal operations"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "math-s1-t2-1",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Measurements",
    subtopics: ["Length", "Mass", "Volume"],
    objectives: ["Measure accurately", "Convert units", "Solve real problems"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "math-s1-t2-2",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Geometry - Lines & Angles",
    subtopics: ["Lines", "Angles", "Triangles"],
    objectives: [
      "Identify geometric terms",
      "Measure angles",
      "Classify shapes",
    ],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "math-s1-t3-1",
    subject: "Mathematics",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Statistics",
    subtopics: ["Data collection", "Representation", "Interpretation"],
    objectives: ["Collect data", "Draw charts", "Interpret information"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["community"],
  },

  // Biology S1
  {
    id: "bio-s1-t1-1",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Biology",
    subtopics: ["What is biology?", "Branches", "Importance"],
    objectives: ["Define biology", "List branches", "Explain importance"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "bio-s1-t1-2",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Living Things",
    subtopics: ["Characteristics", "Classification", "Organization"],
    objectives: [
      "Identify characteristics",
      "Classify organisms",
      "Understand levels",
    ],
    weeks: 2,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "bio-s1-t1-3",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Cell Structure",
    subtopics: ["Cell theory", "Plant vs Animal cells", "Microscope use"],
    objectives: [
      "Explain cell theory",
      "Differentiate cells",
      "Use microscope",
    ],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "bio-s1-t2-1",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Nutrition",
    subtopics: ["Food groups", "Balanced diet", "Digestion"],
    objectives: ["Identify food groups", "Plan diet", "Explain digestion"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["health"],
  },
  {
    id: "bio-s1-t2-2",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Health & Hygiene",
    subtopics: ["Personal hygiene", "Common diseases", "Prevention"],
    objectives: ["Practice hygiene", "Identify diseases", "Apply prevention"],
    weeks: 2,
    competency_focus: "extended",
    cross_cutting_theme: ["health"],
  },
  {
    id: "bio-s1-t3-1",
    subject: "Biology",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Ecosystems",
    subtopics: ["Energy flow", "Food chains", "Environmental conservation"],
    objectives: [
      "Analyze energy flow",
      "Create food chains",
      "Promote conservation",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["climate"],
  },

  // Chemistry S1
  {
    id: "chem-s1-t1-1",
    subject: "Chemistry",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Chemistry",
    subtopics: ["What is chemistry?", "Scientific method", "Lab safety"],
    objectives: [
      "Define chemistry",
      "Apply scientific method",
      "Ensure safety",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "chem-s1-t1-2",
    subject: "Chemistry",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Matter",
    subtopics: ["States of matter", "Physical changes", "Chemical changes"],
    objectives: [
      "Describe states",
      "Differentiate changes",
      "Explain processes",
    ],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "chem-s1-t1-3",
    subject: "Chemistry",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Atoms & Elements",
    subtopics: ["Atomic structure", "Elements", "Periodic table basics"],
    objectives: ["Describe atoms", "Identify elements", "Use periodic table"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "chem-s1-t2-1",
    subject: "Chemistry",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Compounds & Mixtures",
    subtopics: ["Formation", "Separation techniques", "Properties"],
    objectives: ["Form compounds", "Separate mixtures", "Compare properties"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "chem-s1-t3-1",
    subject: "Chemistry",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Acids, Bases & Salts",
    subtopics: ["Properties", "Indicators", "Neutralization"],
    objectives: [
      "Identify acids/bases",
      "Use indicators",
      "Explain neutralization",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Physics S1
  {
    id: "phy-s1-t1-1",
    subject: "Physics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Physics",
    subtopics: ["What is physics?", "Measurement", "Scientific methods"],
    objectives: ["Define physics", "Make measurements", "Apply methods"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "phy-s1-t1-2",
    subject: "Physics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Motion",
    subtopics: ["Speed", "Velocity", "Acceleration"],
    objectives: [
      "Calculate speed",
      "Distinguish velocity",
      "Explain acceleration",
    ],
    weeks: 2,
    competency_focus: "developing",
  },
  {
    id: "phy-s1-t1-3",
    subject: "Physics",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Forces",
    subtopics: ["Types of forces", "Effects", "Newton's laws intro"],
    objectives: ["Identify forces", "Explain effects", "Apply laws"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "phy-s1-t2-1",
    subject: "Physics",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Energy",
    subtopics: ["Forms", "Transformation", "Conservation"],
    objectives: ["Identify forms", "Transform energy", "Apply conservation"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "phy-s1-t3-1",
    subject: "Physics",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Waves",
    subtopics: ["Types", "Properties", "Sound & Light basics"],
    objectives: [
      "Classify waves",
      "Explain properties",
      "Analyze wave behavior",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Geography S1
  {
    id: "geo-s1-t1-1",
    subject: "Geography",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Geography",
    subtopics: ["Definition", "Branches", "Importance"],
    objectives: ["Define geography", "List branches", "Explain relevance"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "geo-s1-t1-2",
    subject: "Geography",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Map Reading",
    subtopics: ["Map types", "Symbols", "Scale"],
    objectives: ["Read maps", "Interpret symbols", "Use scale"],
    weeks: 2,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "geo-s1-t1-3",
    subject: "Geography",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Weather & Climate",
    subtopics: ["Elements", "Factors", "Climate zones"],
    objectives: ["Measure weather", "Analyze factors", "Classify climate"],
    weeks: 3,
    competency_focus: "developing",
    cross_cutting_theme: ["climate"],
  },
  {
    id: "geo-s1-t2-1",
    subject: "Geography",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Rocks & Minerals",
    subtopics: ["Types", "Formation", "Economic importance"],
    objectives: ["Classify rocks", "Explain formation", "Identify uses"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["entrepreneurship"],
  },
  {
    id: "geo-s1-t3-1",
    subject: "Geography",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Population",
    subtopics: ["Distribution", "Migration", "Urbanization"],
    objectives: [
      "Analyze distribution",
      "Explain migration",
      "Evaluate urbanization",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["community"],
  },

  // History S1
  {
    id: "his-s1-t1-1",
    subject: "History",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to History",
    subtopics: ["Definition", "Sources", "Periodization"],
    objectives: ["Define history", "Collect sources", "Apply periodization"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "his-s1-t1-2",
    subject: "History",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Pre-colonial Uganda",
    subtopics: ["Kingdoms", "Trade routes", "Society"],
    objectives: ["Describe kingdoms", "Analyze trade", "Explain society"],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "his-s1-t1-3",
    subject: "History",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Arrival of Explorers",
    subtopics: ["European explorers", "Motives", "Impact"],
    objectives: ["Identify explorers", "Explain motives", "Assess impact"],
    weeks: 3,
    competency_focus: "developing",
  },
  {
    id: "his-s1-t2-1",
    subject: "History",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Colonial Period",
    subtopics: [
      "British administration",
      "Resistance movements",
      "Economic changes",
    ],
    objectives: [
      "Analyze administration",
      "Document resistance",
      "Evaluate changes",
    ],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["gender"],
  },
  {
    id: "his-s1-t3-1",
    subject: "History",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Independence & Nation Building",
    subtopics: [
      "Independence struggle",
      "Post-independence challenges",
      "Regional cooperation",
    ],
    objectives: [
      "Analyze struggle",
      "Evaluate challenges",
      "Explain cooperation",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["peace"],
  },

  // Computer Studies S1
  {
    id: "ict-s1-t1-1",
    subject: "Computer Studies",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to ICT",
    subtopics: ["Computer systems", "Input/Output devices", "Storage"],
    objectives: ["Identify components", "Explain functions", "Use storage"],
    weeks: 1,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "ict-s1-t1-2",
    subject: "Computer Studies",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Operating Systems",
    subtopics: ["Windows basics", "File management", "Settings"],
    objectives: ["Navigate OS", "Manage files", "Configure settings"],
    weeks: 2,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "ict-s1-t1-3",
    subject: "Computer Studies",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Word Processing",
    subtopics: ["Document creation", "Formatting", "Printing"],
    objectives: ["Create documents", "Apply formatting", "Print effectively"],
    weeks: 3,
    competency_focus: "mastered",
    cross_cutting_theme: ["ict"],
  },
  {
    id: "ict-s1-t2-1",
    subject: "Computer Studies",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Spreadsheets",
    subtopics: ["Formulas", "Functions", "Charts"],
    objectives: ["Use formulas", "Apply functions", "Create charts"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["ict", "entrepreneurship"],
  },
  {
    id: "ict-s1-t3-1",
    subject: "Computer Studies",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Internet & Email",
    subtopics: ["Browser use", "Email etiquette", "Online safety"],
    objectives: ["Use browser", "Compose emails", "Stay safe online"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["ict"],
  },

  // Entrepreneurship S1
  {
    id: "ent-s1-t1-1",
    subject: "Entrepreneurship",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Entrepreneurship",
    subtopics: ["Definitions", "Qualities", "Opportunities"],
    objectives: [
      "Define entrepreneurship",
      "Identify qualities",
      "Spot opportunities",
    ],
    weeks: 1,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["entrepreneurship"],
  },
  {
    id: "ent-s1-t1-2",
    subject: "Entrepreneurship",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Business Ideas",
    subtopics: ["Idea generation", "Feasibility", "Market research"],
    objectives: ["Generate ideas", "Assess feasibility", "Research markets"],
    weeks: 2,
    competency_focus: "developing",
    cross_cutting_theme: ["entrepreneurship"],
  },
  {
    id: "ent-s1-t1-3",
    subject: "Entrepreneurship",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Business Plan Basics",
    subtopics: ["Structure", "Components", "Presentation"],
    objectives: ["Structure plans", "Identify components", "Present ideas"],
    weeks: 3,
    competency_focus: "developing",
    cross_cutting_theme: ["entrepreneurship"],
  },
  {
    id: "ent-s1-t2-1",
    subject: "Entrepreneurship",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Record Keeping",
    subtopics: ["Importance", "Books of accounts", "Basics"],
    objectives: [
      "Explain importance",
      "Maintain records",
      "Use basic accounting",
    ],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["entrepreneurship"],
  },
  {
    id: "ent-s1-t3-1",
    subject: "Entrepreneurship",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Marketing",
    subtopics: ["Marketing mix", "Promotion", "Customer relations"],
    objectives: [
      "Apply marketing mix",
      "Promote products",
      "Build customer relations",
    ],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["entrepreneurship"],
  },

  // Religious Education S1
  {
    id: "re-s1-t1-1",
    subject: "Religious Education",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Introduction to Religion",
    subtopics: ["What is religion?", "World religions", "Importance"],
    objectives: ["Define religion", "Compare religions", "Explain importance"],
    weeks: 1,
    competency_focus: "demonstrates",
  },
  {
    id: "re-s1-t1-2",
    subject: "Religious Education",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Bible/ Quran Basics",
    subtopics: ["Scripture overview", "Key teachings", "Application"],
    objectives: [
      "Summarize scripture",
      "Identify teachings",
      "Apply principles",
    ],
    weeks: 2,
    competency_focus: "demonstrates",
  },
  {
    id: "re-s1-t2-1",
    subject: "Religious Education",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Moral Values",
    subtopics: ["Honesty", "Respect", "Service"],
    objectives: ["Practice honesty", "Show respect", "Serve others"],
    weeks: 1,
    competency_focus: "mastered",
    cross_cutting_theme: ["peace"],
  },
  {
    id: "re-s1-t3-1",
    subject: "Religious Education",
    class_level: 1,
    level: "o-level",
    term: 3,
    topic: "Community Service",
    subtopics: ["Help at school", "Help at home", "Help in community"],
    objectives: ["Identify ways to help", "Plan service", "Reflect on impact"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["community"],
  },

  // Physical Education S1
  {
    id: "pe-s1-t1-1",
    subject: "Physical Education",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Health & Fitness",
    subtopics: ["Components of fitness", "Exercise", "Nutrition for sports"],
    objectives: ["Define fitness", "Plan exercises", "Apply nutrition"],
    weeks: 1,
    competency_focus: "demonstrates",
    cross_cutting_theme: ["health"],
  },
  {
    id: "pe-s1-t1-2",
    subject: "Physical Education",
    class_level: 1,
    level: "o-level",
    term: 1,
    topic: "Ball Games",
    subtopics: ["Football basics", "Netball basics", "Volleyball basics"],
    objectives: ["Play football", "Play netball", "Play volleyball"],
    weeks: 2,
    competency_focus: "mastered",
    cross_cutting_theme: ["health"],
  },
  {
    id: "pe-s1-t2-1",
    subject: "Physical Education",
    class_level: 1,
    level: "o-level",
    term: 2,
    topic: "Athletics",
    subtopics: ["Running", "Jumping", "Throwing"],
    objectives: ["Run correctly", "Jump safely", "Throw effectively"],
    weeks: 1,
    competency_focus: "extended",
    cross_cutting_theme: ["health"],
  },
];

// ============================================
// O-LEVEL S2 (Senior Two)
// ============================================

export const S2_ALL_SUBJECTS: NSDCTopic[] = [
  // English S2
  {
    id: "eng-s2-t1-1",
    subject: "English",
    class_level: 2,
    level: "o-level",
    term: 1,
    topic: "Advanced Reading",
    subtopics: ["Critical reading", "Inference", "Analysis"],
    objectives: ["Read critically", "Make inferences", "Analyze text"],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "eng-s2-t1-2",
    subject: "English",
    class_level: 2,
    level: "o-level",
    term: 1,
    topic: "Essay Writing",
    subtopics: ["Essay types", "Structure", "Flow"],
    objectives: ["Write essays", "Organize ideas", "Maintain flow"],
    weeks: 2,
    competency_focus: "mastered",
  },
  {
    id: "eng-s2-t2-1",
    subject: "English",
    class_level: 2,
    level: "o-level",
    term: 2,
    topic: "Grammar - Advanced",
    subtopics: ["Tense", "Voice", "Subject-verb agreement"],
    objectives: ["Master tenses", "Use voice correctly", "Apply agreement"],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "eng-s2-t3-1",
    subject: "English",
    class_level: 2,
    level: "o-level",
    term: 3,
    topic: "Literature",
    subtopics: ["Prose", "Poetry", "Drama"],
    objectives: [
      "Analyze literature forms",
      "Appreciate techniques",
      "Write critically",
    ],
    weeks: 1,
    competency_focus: "extended",
  },

  // Mathematics S2
  {
    id: "math-s2-t1-1",
    subject: "Mathematics",
    class_level: 2,
    level: "o-level",
    term: 1,
    topic: "Algebra - Expressions",
    subtopics: ["Simplification", "Factorisation", "Expansion"],
    objectives: [
      "Simplify expressions",
      "Factorize equations",
      "Expand brackets",
    ],
    weeks: 1,
    competency_focus: "mastered",
  },
  {
    id: "math-s2-t1-2",
    subject: "Mathematics",
    class_level: 2,
    level: "o-level",
    term: 1,
    topic: "Linear Equations",
    subtopics: ["Methods", "Word problems", "Applications"],
    objectives: [
      "Solve linear equations",
      "Apply to problems",
      "Use in real life",
    ],
    weeks: 2,
    competency_focus: "mastered",
  },
  {
    id: "math-s2-t2-1",
    subject: "Mathematics",
    class_level: 2,
    level: "o-level",
    term: 2,
    topic: "Geometry - Angles & Triangles",
    subtopics: ["Angle properties", "Triangle theorems", "Proofs"],
    objectives: [
      "Apply angle properties",
      "Use triangle theorems",
      "Write proofs",
    ],
    weeks: 1,
    competency_focus: "extended",
  },
  {
    id: "math-s2-t3-1",
    subject: "Mathematics",
    class_level: 2,
    level: "o-level",
    term: 3,
    topic: "Probability",
    subtopics: [
      "Basic probability",
      "Mutually exclusive",
      "Independent events",
    ],
    objectives: ["Calculate probability", "Apply rules", "Solve problems"],
    weeks: 1,
    competency_focus: "extended",
  },

  // Add more S2 subjects as needed...
];

// Combine all O-Level (S1-S4)
export const O_LEVEL_TOPICS = [...S1_ALL_SUBJECTS, ...S2_ALL_SUBJECTS];

// Empty placeholders for S3-S4 and A-Level (S5-S6)
// Teachers can populate these based on actual NCDC syllabi

export const S3_ALL_SUBJECTS: NSDCTopic[] = [];
export const S4_ALL_SUBJECTS: NSDCTopic[] = [];
export const S5_ALL_SUBJECTS: NSDCTopic[] = []; // A-Level S5
export const S6_ALL_SUBJECTS: NSDCTopic[] = []; // A-Level S6

// Complete database
export const ALL_NCDC_TOPICS = [
  ...S1_ALL_SUBJECTS,
  ...S2_ALL_SUBJECTS,
  ...S3_ALL_SUBJECTS,
  ...S4_ALL_SUBJECTS,
  ...S5_ALL_SUBJECTS,
  ...S6_ALL_SUBJECTS,
];

// Helper functions
export function getTopicsBySubject(subject: string): NSDCTopic[] {
  return ALL_NCDC_TOPICS.filter((t) => t.subject === subject);
}

export function getTopicsByClass(
  subject: string,
  classLevel: number,
): NSDCTopic[] {
  return ALL_NCDC_TOPICS.filter(
    (t) => t.subject === subject && t.class_level === classLevel,
  );
}

export function getTopicsByTerm(
  subject: string,
  classLevel: number,
  term: number,
): NSDCTopic[] {
  return ALL_NCDC_TOPICS.filter(
    (t) =>
      t.subject === subject && t.class_level === classLevel && t.term === term,
  );
}

export function getTopicsByLevel(level: "o-level" | "a-level"): NSDCTopic[] {
  return ALL_NCDC_TOPICS.filter((t) => t.level === level);
}

export function getSubjectStats() {
  const stats: { [key: string]: number } = {};
  ALL_NCDC_TOPICS.forEach((t) => {
    stats[t.subject] = (stats[t.subject] || 0) + 1;
  });
  return Object.entries(stats).map(([subject, count]) => ({
    subject,
    topics: count,
  }));
}

// For database seed - generates syllabus records for all topics
export function generateSyllabusSeed(
  schoolId: string,
  classId: string,
  subjectId: string,
) {
  const topics = ALL_NCDC_TOPICS.filter(
    (t) =>
      t.subject === subjectId.split("-")[0] ||
      subjectId.includes(t.subject.toLowerCase()),
  );
  return topics.map((topic) => ({
    school_id: schoolId,
    class_id: classId,
    subject_id: subjectId,
    topic: topic.topic,
    subtopics: topic.subtopics,
    term: topic.term,
    weeks_covered: topic.weeks.toString(),
    competency_focus: topic.competency_focus,
    cross_cutting_theme: topic.cross_cutting_theme,
  }));
}
