export interface UgandaDistrictDirectoryEntry {
  district: string;
  subcounties: readonly string[];
  parishes: Record<string, readonly string[]>;
}

export const UGANDA_DISTRICT_DIRECTORY: readonly UgandaDistrictDirectoryEntry[] = [
  {
    district: "Kampala",
    subcounties: ["Central Division", "Kawempe Division", "Makindye Division", "Nakawa Division", "Rubaga Division"],
    parishes: {
      "Central Division": ["Nakasero", "Old Kampala", "Kololo"],
      "Kawempe Division": ["Bwaise", "Kazo", "Kyebando"],
      "Makindye Division": ["Kibuye", "Lukuli", "Nsambya"],
      "Nakawa Division": ["Bugolobi", "Naguru", "Ntinda"],
      "Rubaga Division": ["Mengo", "Mutundwe", "Ndejje"],
    },
  },
  {
    district: "Wakiso",
    subcounties: ["Busiro", "Kyadondo", "Makindye-Ssabagabo", "Entebbe Municipality"],
    parishes: {
      Busiro: ["Bulenga", "Nansana", "Wakiso Town"],
      Kyadondo: ["Kira", "Kyaliwajjala", "Namugongo"],
      "Makindye-Ssabagabo": ["Bunamwaya", "Kansanga", "Seguku"],
      "Entebbe Municipality": ["Katabi", "Division A", "Division B"],
    },
  },
  {
    district: "Mukono",
    subcounties: ["Mukono TC", "Goma", "Ntenjeru", "Nama"],
    parishes: {
      "Mukono TC": ["Central Ward", "Ggulu", "Nsambwe"],
      Goma: ["Kyaggwe", "Mbalala", "Seeta"],
      Ntenjeru: ["Ntenjeru", "Kisoga", "Ntunda"],
      Nama: ["Nama", "Nakisunga", "Bajjo"],
    },
  },
  {
    district: "Jinja",
    subcounties: ["Jinja South", "Jinja North", "Budondo", "Mafubira"],
    parishes: {
      "Jinja South": ["Mpumudde", "Walukuba", "Bugembe"],
      "Jinja North": ["Kimaka", "Nalufenya", "Buwenge"],
      Budondo: ["Buwenge", "Masese", "Wanyange"],
      Mafubira: ["Mafubira", "Kakira", "Wakitaka"],
    },
  },
  {
    district: "Mbale",
    subcounties: ["Industrial Division", "Northern Division", "Wanale", "Bungokho"],
    parishes: {
      "Industrial Division": ["Mission Cell", "Namakwekwe", "Nkoma"],
      "Northern Division": ["Busamaga", "Namatala", "Nakaloke"],
      Wanale: ["Mooni", "Busiu", "Namanyonyi"],
      Bungokho: ["Bumbo", "Bukonde", "Mutoto"],
    },
  },
  {
    district: "Gulu",
    subcounties: ["Pece", "Laroo-Pece", "Bardege", "Layibi"],
    parishes: {
      Pece: ["Pece Prison", "Kasubi", "Bobi"],
      "Laroo-Pece": ["Laroo", "Pawel", "Unyama"],
      Bardege: ["Bardege", "Awach", "Bungatira"],
      Layibi: ["Layibi", "Patiko", "Lacor"],
    },
  },
  {
    district: "Lira",
    subcounties: ["Lira Central", "Ojwina", "Adyel", "Barapwo"],
    parishes: {
      "Lira Central": ["Senior Quarters", "Railway", "Market"],
      Ojwina: ["Ojwina", "Ireda", "Akia"],
      Adyel: ["Adyel", "Ngetta", "Adekokwok"],
      Barapwo: ["Barapwo", "Amach", "Aromo"],
    },
  },
  {
    district: "Masaka",
    subcounties: ["Kimaanya-Kabonera", "Nyendo-Mukungwe", "Kimanya", "Bukakata"],
    parishes: {
      "Kimaanya-Kabonera": ["Kimaanya", "Kabonera", "Bwala"],
      "Nyendo-Mukungwe": ["Nyendo", "Mukungwe", "Kitovu"],
      Kimanya: ["Kimanya", "Ssenyange", "Bwala"],
      Bukakata: ["Bukakata", "Buwunga", "Banda"],
    },
  },
  {
    district: "Mbarara",
    subcounties: ["Nyamitanga", "Kakoba", "Kamukuzi", "Biharwe"],
    parishes: {
      Nyamitanga: ["Nyamitanga", "Kenkombe", "Rwentondo"],
      Kakoba: ["Kakoba", "Ruti", "Katete"],
      Kamukuzi: ["Kamukuzi", "Kakyeka", "Kagongi"],
      Biharwe: ["Biharwe", "Rubaya", "Bwizibwera"],
    },
  },
  {
    district: "Fort Portal",
    subcounties: ["Central Division", "South Division", "East Division", "West Division"],
    parishes: {
      "Central Division": ["Rwengoma", "Boma", "Kagote"],
      "South Division": ["Kijanju", "Buhinga", "Kitumba"],
      "East Division": ["Kisenyi", "Bukwali", "Karambi"],
      "West Division": ["Hakibaale", "Mugunu", "Kitembe"],
    },
  },
  {
    district: "Kabale",
    subcounties: ["Central Division", "Southern Division", "Northern Division", "Katuna"],
    parishes: {
      "Central Division": ["Central Ward", "Kirigime", "Rushaki"],
      "Southern Division": ["Nyabikoni", "Rugarama", "Kikungiri"],
      "Northern Division": ["Buhara", "Kyanamira", "Kyanamukaka"],
      Katuna: ["Katuna", "Kyanika", "Muko"],
    },
  },
  {
    district: "Soroti",
    subcounties: ["Soroti East", "Soroti West", "Aukot", "Gweri"],
    parishes: {
      "Soroti East": ["Awoja", "Asuret", "Pamba"],
      "Soroti West": ["Madera", "Nakatunya", "Awoja Bridge"],
      Aukot: ["Aukot", "Katine", "Arapai"],
      Gweri: ["Gweri", "Awoja", "Tubur"],
    },
  },
  {
    district: "Arua",
    subcounties: ["Arua Central", "River Oli", "Ayivu", "Vurra"],
    parishes: {
      "Arua Central": ["Bazaar", "Mvara", "Awindiri"],
      "River Oli": ["Pokea", "Pajulu", "Onduparaka"],
      Ayivu: ["Ayivu", "Ediofe", "Pajulu"],
      Vurra: ["Odravu", "Logiri", "Vurra"],
    },
  },
  {
    district: "Hoima",
    subcounties: ["Mparo", "Kahoora", "Buhanika", "Kyabigambire"],
    parishes: {
      Mparo: ["Mparo", "Bulera", "Kibingo"],
      Kahoora: ["Kahoora", "Bwikya", "Busiisi"],
      Buhanika: ["Buhanika", "Kigorobya", "Bombo"],
      Kyabigambire: ["Kyabigambire", "Kiganja", "Buseruka"],
    },
  },
  {
    district: "Masindi",
    subcounties: ["Central Division", "Nyangahya", "Karujubu", "Kimengo"],
    parishes: {
      "Central Division": ["Central", "Kijura", "Kibwona"],
      Nyangahya: ["Nyangahya", "Kimina", "Nyabinyegera"],
      Karujubu: ["Karujubu", "Bwijanga", "Pakanyi"],
      Kimengo: ["Kimengo", "Miirya", "Kisanja"],
    },
  },
  {
    district: "Tororo",
    subcounties: ["Eastern Division", "Western Division", "Mukuju", "Malaba"],
    parishes: {
      "Eastern Division": ["Central Ward", "Kasoli", "Osukuru"],
      "Western Division": ["Western Ward", "Molo", "Petta"],
      Mukuju: ["Mukuju", "Nagongera", "Merikit"],
      Malaba: ["Malaba", "Angorom", "Iyolwa"],
    },
  },
  {
    district: "Busia",
    subcounties: ["Busia TC", "Masafu", "Lumino", "Buteba"],
    parishes: {
      "Busia TC": ["Marachi", "Solo", "Dabani"],
      Masafu: ["Masafu", "Sikuda", "Buchicha"],
      Lumino: ["Lumino", "Majanji", "Buhehe"],
      Buteba: ["Buteba", "Bulumbi", "Buyengo"],
    },
  },
  {
    district: "Iganga",
    subcounties: ["Iganga Central", "Nakalama", "Bulamagi", "Nambale"],
    parishes: {
      "Iganga Central": ["Central Ward", "Busei", "Mbulamuti"],
      Nakalama: ["Nakalama", "Buwenge", "Nabitende"],
      Bulamagi: ["Bulamagi", "Nawandala", "Bukoyo"],
      Nambale: ["Nambale", "Nawanyago", "Namungalwe"],
    },
  },
  {
    district: "Kamuli",
    subcounties: ["Northern Division", "Southern Division", "Bugabula", "Kitayunjwa"],
    parishes: {
      "Northern Division": ["Northern Ward", "Kasambira", "Mbulamuti"],
      "Southern Division": ["Southern Ward", "Namasagali", "Balawoli"],
      Bugabula: ["Bugabula", "Nabwigulu", "Buwenge"],
      Kitayunjwa: ["Kitayunjwa", "Nankandulo", "Mbulamuti"],
    },
  },
  {
    district: "Apac",
    subcounties: ["Apoi", "Ibuje", "Chegere", "Maruzi"],
    parishes: {
      Apoi: ["Apoi", "Aduku", "Abongomola"],
      Ibuje: ["Ibuje", "Arocha", "Atopi"],
      Chegere: ["Chegere", "Akokoro", "Inomo"],
      Maruzi: ["Maruzi", "Akwon", "Atar"],
    },
  },
  {
    district: "Entebbe",
    subcounties: ["Division A", "Division B", "Katabi", "Kitoro"],
    parishes: {
      "Division A": ["Kiwafu", "Katabi", "Kiwafu West"],
      "Division B": ["Bulega", "Kitoro", "Lugonjo"],
      Katabi: ["Katabi", "Abayita Ababiri", "Lweza"],
      Kitoro: ["Kitoro", "Kigungu", "Nakiwogo"],
    },
  },
  {
    district: "Kasese",
    subcounties: ["Kasese Municipality", "Bulembia", "Kisinga", "Hima"],
    parishes: {
      "Kasese Municipality": ["Central", "Nyamwamba", "Kilembe"],
      Bulembia: ["Bulembia", "Kyalhumba", "Kitswamba"],
      Kisinga: ["Kisinga", "Munkunyu", "Kagando"],
      Hima: ["Hima", "Karusandara", "Muhokya"],
    },
  },
  {
    district: "Kitgum",
    subcounties: ["Kitgum Municipality", "Labongo", "Mucwini", "Pajimo"],
    parishes: {
      "Kitgum Municipality": ["Central", "Pager", "Pandwong"],
      Labongo: ["Labongo", "Namokora", "Akwang"],
      Mucwini: ["Mucwini", "Lukwor", "Akwang"],
      Pajimo: ["Pajimo", "Palabek", "Akworo"],
    },
  },
  {
    district: "Moroto",
    subcounties: ["South Division", "North Division", "Katikekile", "Nadunget"],
    parishes: {
      "South Division": ["South Ward", "Naitakwae", "Nadunget"],
      "North Division": ["North Ward", "Camp Swahili", "Singila"],
      Katikekile: ["Katikekile", "Lopedot", "Nadiket"],
      Nadunget: ["Nadunget", "Tapac", "Rupa"],
    },
  },
  // Additional districts (subcounties only, no parish detail)
  { district: "Mityana", subcounties: ["Mityana TC", "Busimbi", "Maanyi", "Kalangalo"], parishes: {} },
  { district: "Mpigi", subcounties: ["Mpigi TC", "Bujuuko", "Muduuma", "Nkozi"], parishes: {} },
  { district: "Kayunga", subcounties: ["Kayunga TC", "Kangulumira", "Busaana", "Nazigo"], parishes: {} },
  { district: "Luweero", subcounties: ["Luweero TC", "Wobulenzi", "Bamunanika", "Katikamu"], parishes: {} },
  { district: "Nakasongola", subcounties: ["Nakasongola TC", "Lwampanga", "Kakooge", "Wabinyonyi"], parishes: {} },
  { district: "Rakai", subcounties: ["Rakai TC", "Kalisizo", "Kyotera", "Kabira"], parishes: {} },
  { district: "Sembabule", subcounties: ["Sembabule TC", "Mateete", "Lugusulu", "Ntusi"], parishes: {} },
  { district: "Kalangala", subcounties: ["Kalangala TC", "Bufumira", "Bujumba", "Mugoye"], parishes: {} },
  { district: "Lyantonde", subcounties: ["Lyantonde TC", "Mpumudde", "Kaliiro"], parishes: {} },
  { district: "Buikwe", subcounties: ["Lugazi MC", "Njeru TC", "Ssi-Bukunja", "Nkokonjeru"], parishes: {} },
  { district: "Buvuma", subcounties: ["Buvuma TC", "Busamuzi", "Nairambi"], parishes: {} },
  { district: "Gomba", subcounties: ["Kanoni TC", "Mpenja", "Kabulasoke"], parishes: {} },
  { district: "Butambala", subcounties: ["Gombe TC", "Budde", "Butambala"], parishes: {} },
  { district: "Kiboga", subcounties: ["Kiboga TC", "Lwamata", "Kapeke", "Bukomero"], parishes: {} },
  { district: "Kyankwanzi", subcounties: ["Kyankwanzi TC", "Ntwetwe", "Gayaza", "Nsambya"], parishes: {} },
  { district: "Mubende", subcounties: ["Mubende MC", "Kasambya", "Kitenga", "Bagezza"], parishes: {} },
  { district: "Kyegegwa", subcounties: ["Kyegegwa TC", "Hapuuyo", "Kasule", "Mpara"], parishes: {} },
  { district: "Kakumiro", subcounties: ["Kakumiro TC", "Kibaale", "Bwanswa"], parishes: {} },
  { district: "Kibaale", subcounties: ["Kibaale TC", "Kagadi", "Muhorro", "Buyaga"], parishes: {} },
  { district: "Ntungamo", subcounties: ["Ntungamo MC", "Ruhaama", "Kajara", "Rwahi"], parishes: {} },
  { district: "Bushenyi", subcounties: ["Bushenyi-Ishaka MC", "Kyamuhunga", "Kakanju"], parishes: {} },
  { district: "Sheema", subcounties: ["Sheema TC", "Kibingo", "Masheruka", "Shuuku"], parishes: {} },
  { district: "Rukungiri", subcounties: ["Rukungiri MC", "Buyanja", "Bwambara", "Kebisoni"], parishes: {} },
  { district: "Kanungu", subcounties: ["Kanungu TC", "Kambuga", "Kihihi", "Butogota"], parishes: {} },
  { district: "Kisoro", subcounties: ["Kisoro MC", "Nyarusiza", "Muramba", "Nyakabande"], parishes: {} },
  { district: "Isingiro", subcounties: ["Isingiro TC", "Endiinzi", "Kabingo", "Ngarama"], parishes: {} },
  { district: "Ibanda", subcounties: ["Ibanda MC", "Bisheshe", "Kikyenkye", "Nyabuhikye"], parishes: {} },
  { district: "Kiruhura", subcounties: ["Kiruhura TC", "Kanyaryeru", "Kinoni", "Sanga"], parishes: {} },
  { district: "Kabarole", subcounties: ["Fort Portal TC", "Burahya", "Busoro", "Rwimi"], parishes: {} },
  { district: "Bundibugyo", subcounties: ["Bundibugyo TC", "Busaru", "Harugali", "Kirumya"], parishes: {} },
  { district: "Ntoroko", subcounties: ["Ntoroko TC", "Rwebisengo", "Kanara"], parishes: {} },
  { district: "Bunyangabu", subcounties: ["Kibiito TC", "Kateebwa", "Rwimi"], parishes: {} },
  { district: "Kamwenge", subcounties: ["Kamwenge TC", "Biguli", "Kibale", "Nkoma"], parishes: {} },
  { district: "Kyenjojo", subcounties: ["Kyenjojo TC", "Katooke", "Butunduzi", "Hapuuyo"], parishes: {} },
  { district: "Kitagwenda", subcounties: ["Kitagwenda TC", "Kitagwenda", "Mahyoro"], parishes: {} },
  { district: "Pallisa", subcounties: ["Pallisa TC", "Agule", "Butebo", "Gogonyo"], parishes: {} },
  { district: "Budaka", subcounties: ["Budaka TC", "Kameruka", "Kamonkoli"], parishes: {} },
  { district: "Butaleja", subcounties: ["Butaleja TC", "Busolwe", "Mazimasa"], parishes: {} },
  { district: "Namutumba", subcounties: ["Namutumba TC", "Bulange", "Ivukula"], parishes: {} },
  { district: "Bugiri", subcounties: ["Bugiri MC", "Buwunga", "Kapyanga", "Nankoma"], parishes: {} },
  { district: "Namayingo", subcounties: ["Namayingo TC", "Banda", "Buyinja", "Lolwe"], parishes: {} },
  { district: "Mayuge", subcounties: ["Mayuge TC", "Baitambogwe", "Buwaiswa", "Kityerera"], parishes: {} },
  { district: "Buyende", subcounties: ["Buyende TC", "Bugaya", "Kagulu", "Nkondo"], parishes: {} },
  { district: "Kaliro", subcounties: ["Kaliro TC", "Bumanya", "Namugongo", "Nawaikoke"], parishes: {} },
  { district: "Luuka", subcounties: ["Luuka TC", "Bukanga", "Ikumbya", "Irongo"], parishes: {} },
  { district: "Sironko", subcounties: ["Sironko TC", "Budadiri", "Masaba", "Zesui"], parishes: {} },
  { district: "Manafwa", subcounties: ["Manafwa TC", "Bubulo", "Bubutu", "Butiru"], parishes: {} },
  { district: "Bududa", subcounties: ["Bududa TC", "Bushika", "Bududa", "Bukigai"], parishes: {} },
  { district: "Bulambuli", subcounties: ["Bulambuli TC", "Bulegeni", "Sisiyi", "Bwikhonge"], parishes: {} },
  { district: "Kapchorwa", subcounties: ["Kapchorwa TC", "Kween", "Sipi", "Tegeres"], parishes: {} },
  { district: "Kumi", subcounties: ["Kumi MC", "Kanyum", "Ongino", "Mukongoro"], parishes: {} },
  { district: "Ngora", subcounties: ["Ngora TC", "Kapir", "Mukura"], parishes: {} },
  { district: "Serere", subcounties: ["Serere TC", "Bugondo", "Kadungulu", "Olio"], parishes: {} },
  { district: "Katakwi", subcounties: ["Katakwi TC", "Kapujan", "Ngariam", "Toroma"], parishes: {} },
  { district: "Amuria", subcounties: ["Amuria TC", "Abarilela", "Kapelebyong", "Wera"], parishes: {} },
  { district: "Kaberamaido", subcounties: ["Kaberamaido TC", "Alwa", "Kobulubulu", "Otuboi"], parishes: {} },
  { district: "Dokolo", subcounties: ["Dokolo TC", "Agwata", "Batta", "Kangai"], parishes: {} },
  { district: "Alebtong", subcounties: ["Alebtong TC", "Abako", "Aloi", "Amugo"], parishes: {} },
  { district: "Otuke", subcounties: ["Otuke TC", "Adwari", "Okwang", "Olilim"], parishes: {} },
  { district: "Kole", subcounties: ["Kole TC", "Aboke", "Alito", "Bala"], parishes: {} },
  { district: "Oyam", subcounties: ["Oyam TC", "Aber", "Iceme", "Minakulu"], parishes: {} },
  { district: "Pader", subcounties: ["Pader TC", "Awere", "Atanga", "Lacekocot"], parishes: {} },
  { district: "Agago", subcounties: ["Agago TC", "Kalongo", "Lira Palwo", "Patongo"], parishes: {} },
  { district: "Lamwo", subcounties: ["Lamwo TC", "Agoro", "Padibe", "Palabek"], parishes: {} },
  { district: "Amuru", subcounties: ["Amuru TC", "Atiak", "Lamogi", "Pabbo"], parishes: {} },
  { district: "Nwoya", subcounties: ["Nwoya TC", "Anaka", "Koch-Goma", "Purongo"], parishes: {} },
  { district: "Omoro", subcounties: ["Omoro TC", "Lakwana", "Bobi", "Ongako"], parishes: {} },
  { district: "Adjumani", subcounties: ["Adjumani TC", "Ciforo", "Dzaipi", "Pakele"], parishes: {} },
  { district: "Moyo", subcounties: ["Moyo TC", "Metu", "Laropi"], parishes: {} },
  { district: "Yumbe", subcounties: ["Yumbe TC", "Kei Bridge", "Midigo", "Romogi"], parishes: {} },
  { district: "Koboko", subcounties: ["Koboko MC", "Lobule", "Ludara", "Kuluba"], parishes: {} },
  { district: "Maracha", subcounties: ["Maracha TC", "Nyadri", "Oluvu", "Oleba"], parishes: {} },
  { district: "Nebbi", subcounties: ["Nebbi MC", "Erussi", "Kucwiny", "Pakwach"], parishes: {} },
  { district: "Zombo", subcounties: ["Zombo TC", "Paidha", "Warr", "Zeu"], parishes: {} },
  { district: "Pakwach", subcounties: ["Pakwach TC", "Panyango", "Panyimur"], parishes: {} },
  { district: "Buliisa", subcounties: ["Buliisa TC", "Biiso", "Buliisa", "Kigwera"], parishes: {} },
  { district: "Kiryandongo", subcounties: ["Kiryandongo TC", "Bweyale", "Kigumba", "Mutunda"], parishes: {} },
  { district: "Kagadi", subcounties: ["Kagadi TC", "Mabaale", "Muhorro", "Ndaiga"], parishes: {} },
  { district: "Rubanda", subcounties: ["Rubanda TC", "Bufundi", "Hamurwa", "Muko"], parishes: {} },
  { district: "Rukiga", subcounties: ["Rukiga TC", "Kamwezi", "Rwamucucu"], parishes: {} },
  { district: "Mitooma", subcounties: ["Mitooma TC", "Kanyabwanga", "Kashenshero"], parishes: {} },
  { district: "Buhweju", subcounties: ["Buhweju TC", "Engaju", "Bihanga"], parishes: {} },
  { district: "Rubirizi", subcounties: ["Rubirizi TC", "Bunyaruguru", "Katerera", "Magambo"], parishes: {} },
  { district: "Lwengo", subcounties: ["Lwengo TC", "Kisekka", "Ndagwe"], parishes: {} },
  { district: "Kyotera", subcounties: ["Kyotera TC", "Kabira", "Kasaali", "Lwanda"], parishes: {} },
  { district: "Napak", subcounties: ["Napak TC", "Lokopo", "Lorengecora", "Matany"], parishes: {} },
  { district: "Nakapiripirit", subcounties: ["Nakapiripirit TC", "Lorengedwat", "Nabilatuk"], parishes: {} },
  { district: "Amudat", subcounties: ["Amudat TC", "Karita", "Loroo"], parishes: {} },
  { district: "Kotido", subcounties: ["Kotido TC", "Kacheri", "Panyangara", "Rengen"], parishes: {} },
  { district: "Abim", subcounties: ["Abim TC", "Lotuke", "Morulem", "Alerek"], parishes: {} },
  { district: "Kaabong", subcounties: ["Kaabong TC", "Dodoth", "Loyoro", "Sidok"], parishes: {} },
  { district: "Nabilatuk", subcounties: ["Nabilatuk TC", "Lolachat", "Lorengedwat"], parishes: {} },
  { district: "Kapelebyong", subcounties: ["Kapelebyong TC", "Acowa", "Okungur"], parishes: {} },
  { district: "Kwania", subcounties: ["Kwania TC", "Aduku", "Inomo", "Nambieso"], parishes: {} },
  { district: "Amolatar", subcounties: ["Amolatar TC", "Awelo", "Muntu", "Namasale"], parishes: {} },
  { district: "Kalaki", subcounties: ["Kalaki TC", "Gadumire", "Lwala"], parishes: {} },
  { district: "Madi-Okollo", subcounties: ["Madi-Okollo TC", "Okollo", "Rigbo"], parishes: {} },
  { district: "Obongi", subcounties: ["Obongi TC", "Itula", "Kei"], parishes: {} },
  { district: "Terego", subcounties: ["Terego TC", "Omugo", "Uleppi", "Aii-vu"], parishes: {} },
  { district: "Kween", subcounties: ["Kween TC", "Binyiny", "Kwosir", "Ngenge"], parishes: {} },
  { district: "Namisindwa", subcounties: ["Namisindwa TC", "Bukhabusi", "Lwaso"], parishes: {} },
  { district: "Butebo", subcounties: ["Butebo TC", "Kabwangasi", "Petete"], parishes: {} },
  { district: "Kibuku", subcounties: ["Kibuku TC", "Kadama", "Tirinyi"], parishes: {} },
  { district: "Bugweri", subcounties: ["Bugweri TC", "Idudi", "Nawaningi"], parishes: {} },
  { district: "Kassanda", subcounties: ["Kassanda TC", "Kalwana", "Myanzi"], parishes: {} },
  { district: "Kikuube", subcounties: ["Kikuube TC", "Buhaguzi", "Kabwoya"], parishes: {} },
] as const;

export function getDistrictOptions() {
  return UGANDA_DISTRICT_DIRECTORY.map((entry) => ({
    value: entry.district,
    label: entry.district,
  })).sort((a, b) => a.label.localeCompare(b.label));
}

export function getSubcountyOptions(district?: string) {
  const entry = UGANDA_DISTRICT_DIRECTORY.find((item) => item.district === district);
  return (entry?.subcounties || []).map((subcounty) => ({
    value: subcounty,
    label: subcounty,
  }));
}

export function getParishOptions(district?: string, subcounty?: string) {
  const entry = UGANDA_DISTRICT_DIRECTORY.find((item) => item.district === district);
  return (entry?.parishes[subcounty || ""] || []).map((parish) => ({
    value: parish,
    label: parish,
  }));
}
