/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--primary)',
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          400: 'var(--primary-400)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
          800: 'var(--primary-800)',
          900: 'var(--primary-900)',
        },
        surface: {
          DEFAULT: 'var(--surface)',
          brightest: 'var(--surface-brightest)',
          bright: 'var(--surface-bright)',
          dim: 'var(--surface-dim)',
          container: 'var(--surface-container)',
          'container-high': 'var(--surface-container-high)',
          'container-highest': 'var(--surface-container-highest)',
          'container-low': 'var(--surface-container-low)',
          'container-lowest': 'var(--surface-container-lowest)',
          lowest: 'var(--surface-lowest)',
        },
        onSurface: {
          DEFAULT: 'var(--on-surface)',
          variant: 'var(--on-surface-variant)',
        },
        outline: {
          DEFAULT: 'var(--outline)',
          variant: 'var(--outline-variant)',
        },
        background: 'var(--background)',
        'on-background': 'var(--on-background)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'on-primary': 'var(--on-primary)',
        'on-secondary': 'var(--on-secondary)',
        error: 'var(--error)',
      },
      backgroundColor: {
        surface: {
          DEFAULT: 'var(--surface)',
          brightest: 'var(--surface-brightest)',
          bright: 'var(--surface-bright)',
          dim: 'var(--surface-dim)',
          container: 'var(--surface-container)',
          'container-low': 'var(--surface-container-low)',
          'container-lowest': 'var(--surface-container-lowest)',
          lowest: 'var(--surface-lowest)',
        },
      },
      borderColor: {
        DEFAULT: 'var(--border)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
      },
      textColor: {
        onSurface: 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        primary: 'var(--primary)',
      },
      fontFamily: {
        headline: ['Sora', 'sans-serif'],
        heading: ['Sora', 'sans-serif'],
        body: ['Lato', 'system-ui', '-apple-system', 'sans-serif'],
        label: ['Lato', 'sans-serif'],
        sans: ['Lato', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      boxShadow: {
        'xl': '0 10px 40px -4px rgba(0, 32, 69, 0.06)',
        '2xl': '0 24px 48px -12px rgba(0, 32, 69, 0.06)',
        'primary': '0 8px 16px -4px rgba(0, 32, 69, 0.1)',
      },
    },
  },
  plugins: [],
}