"use client";
import {
  useState,
  useRef,
  forwardRef,
  useImperativeHandle,
  useEffect,
} from "react";
import MaterialIcon from "@/components/MaterialIcon";
import { useToast } from "@/components/Toast";
import { t } from "@/i18n";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface PrintHandle {
  open: (content: React.ReactNode, options?: PrintOptions) => void;
  close: () => void;
}

interface PrintOptions {
  title?: string;
  format?: "a4" | "letter" | "receipt";
  orientation?: "portrait" | "landscape";
  showDate?: boolean;
  schoolHeader?: boolean;
}

interface PrintContent {
  node: React.ReactNode;
  options: PrintOptions;
}

const defaultOptions: PrintOptions = {
  title: "Document",
  format: "a4",
  orientation: "portrait",
  showDate: true,
  schoolHeader: true,
};

export const PRINT_FORMATS = {
  a4: { width: 210, height: 297, name: "A4" },
  letter: { width: 216, height: 279, name: "Letter" },
  receipt: { width: 80, height: "auto", name: "Receipt" },
};

export const UnifiedPrint = forwardRef<PrintHandle>(
  function UnifiedPrint(_, ref) {
    const toast = useToast();
    const [isOpen, setIsOpen] = useState(false);
    const [content, setContent] = useState<PrintContent | null>(null);
    const printRef = useRef<HTMLDivElement>(null);

    useImperativeHandle(ref, () => ({
      open: (node, options = {}) => {
        setContent({ node, options: { ...defaultOptions, ...options } });
        setIsOpen(true);
      },
      close: () => {
        setIsOpen(false);
        setContent(null);
      },
    }));

    useEffect(() => {
      return () => {
        const iframe = document.getElementById("print-iframe");
        if (iframe) iframe.remove();
      };
    }, []);

    const getPrintHTML = () => {
      if (!printRef.current) return "";
      const opts = content?.options || defaultOptions;
      const format = PRINT_FORMATS[opts.format || "a4"];
      const isReceipt = opts.format === "receipt";
      const printContent = printRef.current.innerHTML;
      return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <title>${opts.title || "Print"}</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            ${
              isReceipt
                ? `
              width: 80mm;
              padding: 5mm;
              font-size: 12px;
            `
                : `
              width: ${format.width}mm;
              min-height: ${format.height}mm;
              padding: 15mm;
            `
            }
          }
          .header { text-align: center; margin-bottom: 15px; }
          .header h1 { font-size: ${isReceipt ? "14px" : "18px"}; margin-bottom: 5px; }
          .header p { font-size: ${isReceipt ? "10px" : "12px"}; color: #666; }
          .content { line-height: 1.5; }
          .footer { 
            margin-top: 20px; 
            padding-top: 10px; 
            border-top: 1px dashed #ccc; 
            text-align: center; 
            font-size: 10px; 
            color: #999; 
          }
          table { width: 100%; border-collapse: collapse; margin: 10px 0; }
          th, td { 
            border: 1px solid #ddd; 
            padding: ${isReceipt ? "3px" : "8px"}; 
            text-align: left;
            font-size: ${isReceipt ? "10px" : "12px"};
          }
          th { background: #f5f5f5; font-weight: 600; }
          .print-date { text-align: right; font-size: 10px; color: #999; margin-bottom: 10px; }
          @media print {
            body { padding: 0; }
            @page { 
              size: ${opts.orientation === "landscape" ? "landscape" : "portrait"}; 
              margin: 10mm;
            }
          }
        </style>
      </head>
      <body>
        ${opts.showDate !== false ? `<div class="print-date">Printed: ${new Date().toLocaleString()}</div>` : ""}
        <div class="content">
          ${printContent}
        </div>
        <div class="footer">
          Generated by SkulMate OS
        </div>
      </body>
      </html>
    `;
    };

    const handlePrint = () => {
      const html = getPrintHTML();
      if (!html) return;

      let iframe = document.getElementById("print-iframe") as HTMLIFrameElement;
      if (!iframe) {
        iframe = document.createElement("iframe");
        iframe.id = "print-iframe";
        iframe.style.cssText =
          "position:absolute;width:0;height:0;border:none;overflow:hidden;";
        document.body.appendChild(iframe);
      }

      const opts = content?.options || defaultOptions;
      iframe.title = opts.title || "Print";

      const onLoad = () => {
        try {
          iframe.contentWindow?.focus();
          iframe.contentWindow?.print();
        } catch {
          toast?.error("Printing failed. Please use Ctrl+P/Cmd+P instead.");
        }
        iframe.removeEventListener("load", onLoad);
      };
      iframe.addEventListener("load", onLoad);

      iframe.srcdoc = html;
    };

    const handleDownloadPDF = () => {
      if (!printRef.current) return;
      const opts = content?.options || defaultOptions;
      const isReceipt = opts.format === "receipt";

      const doc = new jsPDF({
        orientation:
          opts.orientation === "landscape" ? "landscape" : "portrait",
        unit: "mm",
        format: isReceipt ? [80, 200] : "a4",
      });

      doc.setFontSize(isReceipt ? 10 : 14);
      doc.setFont("helvetica", "bold");
      doc.text(
        opts.title || "Document",
        isReceipt ? 40 : 105,
        isReceipt ? 10 : 15,
        { align: "center" },
      );

      if (opts.showDate !== false) {
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.text(
          `Generated: ${new Date().toLocaleString()}`,
          isReceipt ? 40 : 195,
          isReceipt ? 15 : 10,
          { align: "right" },
        );
      }

      const tables = printRef.current.querySelectorAll("table");
      if (tables.length > 0) {
        tables.forEach((table) => {
          autoTable(doc, {
            html: table as HTMLTableElement,
            startY: isReceipt ? 18 : 22,
            styles: { fontSize: isReceipt ? 7 : 9 },
            headStyles: { fillColor: [30, 58, 95], textColor: 255 },
          });
        });
      } else {
        const textContent = printRef.current.innerText || "";
        doc.setFontSize(isReceipt ? 8 : 10);
        doc.setFont("helvetica", "normal");
        const lines = doc.splitTextToSize(textContent, isReceipt ? 70 : 180);
        doc.text(lines, isReceipt ? 5 : 15, isReceipt ? 22 : 25);
      }

      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(150);
      const pageHeight = doc.internal.pageSize.height;
      doc.text("Generated by SkoolMate OS", isReceipt ? 40 : 105, pageHeight - 5, {
        align: "center",
      });

      doc.save(
        `${(opts.title || "document").replace(/\s+/g, "_").toLowerCase()}.pdf`,
      );
      toast?.success("PDF downloaded successfully");
    };

    if (!isOpen) return null;

    return (
      <div
        style={{
          position: "fixed",
          inset: 0,
          background: "rgba(0,0,0,0.7)",
          zIndex: 9999,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            background: "var(--surface)",
            borderRadius: "var(--r2)",
            width: "95vw",
            maxWidth: 900,
            height: "90vh",
            display: "flex",
            flexDirection: "column",
            overflow: "hidden",
          }}
        >
          {/* Header */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              padding: "16px 20px",
              borderBottom: "1px solid var(--border)",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
              <MaterialIcon
                icon="print"
                style={{ fontSize: 24, color: "var(--t2)" }}
              />
              <div>
                <div
                  style={{ fontSize: 16, fontWeight: 600, color: "var(--t1)" }}
                >
                  {t("print.printPreview")}
                </div>
                <div style={{ fontSize: 12, color: "var(--t3)" }}>
                  {content?.options.title || "Document"}
                </div>
              </div>
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <button onClick={handleDownloadPDF} className="btn btn-ghost">
                <MaterialIcon icon="download" style={{ fontSize: 18 }} />
                {t("print.savePdf")}
              </button>
              <button onClick={handlePrint} className="btn btn-primary">
                <MaterialIcon icon="print" style={{ fontSize: 18 }} />
                {t("print.printNow")}
              </button>
              <button
                onClick={() => setIsOpen(false)}
                className="btn btn-ghost"
              >
                <MaterialIcon icon="close" style={{ fontSize: 18 }} />
              </button>
            </div>
          </div>

          {/* Preview */}
          <div
            style={{
              flex: 1,
              overflow: "auto",
              background: "#e5e5e5",
              padding: 20,
              display: "flex",
              justifyContent: "center",
            }}
          >
            <div
              ref={printRef}
              style={{
                background: "#fff",
                boxShadow: "0 4px 20px rgba(0,0,0,0.2)",
                minWidth: content?.options.format === "receipt" ? 280 : "auto",
                maxWidth: content?.options.format === "receipt" ? 320 : 794,
                padding: content?.options.format === "receipt" ? 20 : 40,
              }}
            >
              {content?.node}
            </div>
          </div>

          {/* Footer */}
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              padding: "12px 20px",
              borderTop: "1px solid var(--border)",
              fontSize: 12,
              color: "var(--t3)",
            }}
          >
            <div>
              Format: {PRINT_FORMATS[content?.options.format || "a4"].name} •
              {content?.options.orientation === "landscape"
                ? " Landscape"
                : " Portrait"}
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <span>Tip: Use Ctrl+P (Cmd+P on Mac) to print</span>
            </div>
          </div>
        </div>
      </div>
    );
  },
);

export function usePrint() {
  const printRef = useRef<PrintHandle>(null);

  const openPrint = (content: React.ReactNode, options?: PrintOptions) => {
    printRef.current?.open(content, options);
  };

  const closePrint = () => {
    printRef.current?.close();
  };

  return {
    printRef: printRef as React.RefObject<PrintHandle>,
    openPrint,
    closePrint,
  };
}
